#!/bin/sh
wget -c http://archive.ubuntu.com/ubuntu/pool/main/i/init-system-helpers/init_1.57_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/u/ubuntu-meta/ubuntu-minimal_1.450.2_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/u/ubuntu-meta/ubuntu-standard_1.450.2_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/c/cinnamon-desktop-environment/cinnamon-core_4.5+really4.4.1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/c/cinnamon-desktop-environment/cinnamon-desktop-environment_4.5+really4.4.1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/d/debichem/debichem-molecular-modelling_0.0.10_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/d/debian-electronics/electronics-all_0.3_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/d/debian-electronics/electronics-analog_0.3_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/d/debian-electronics/electronics-asic-dev_0.3_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/d/debian-electronics/electronics-cad-gui_0.3_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/d/debian-electronics/electronics-digital_0.3_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/d/debian-electronics/electronics-doc_0.3_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/d/debian-electronics/electronics-dsp-dev_0.3_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/d/debian-electronics/electronics-fpga-dev_0.3_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/d/debian-electronics/electronics-gadgets_0.3_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/d/debian-electronics/electronics-measurements_0.3_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/d/debian-electronics/electronics-microcontrollers_0.3_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/d/debian-electronics/electronics-pcb_0.3_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/d/debian-electronics/electronics-radio-dev_0.3_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/d/debian-electronics/electronics-simulation_0.3_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/f/fonts-indic/fonts-indic_1.3_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/f/forensics-all/forensics-all_3.18_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/f/forensics-all/forensics-all-gui_3.18_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/f/forensics-extra/forensics-extra_2.14_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/f/forensics-extra/forensics-extra-gui_2.14_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/f/forensics-extra/forensics-full_2.14_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/d/debian-games/games-adventure_2.2ubuntu3_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/d/debian-games/games-all_2.2ubuntu3_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/d/debian-games/games-arcade_2.2ubuntu3_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/d/debian-games/games-board_2.2ubuntu3_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/d/debian-games/games-c++-dev_2.2ubuntu3_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/d/debian-games/games-card_2.2ubuntu3_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/d/debian-games/games-chess_2.2ubuntu3_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/d/debian-games/games-console_2.2ubuntu3_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/d/debian-games/games-content-dev_2.2ubuntu3_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/d/debian-games/games-education_2.2ubuntu3_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/d/debian-games/games-emulator_2.2ubuntu3_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/d/debian-games/games-finest_2.2ubuntu3_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/d/debian-games/games-finest-light_2.2ubuntu3_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/d/debian-games/games-fps_2.2ubuntu3_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/d/debian-games/games-java-dev_2.2ubuntu3_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/d/debian-games/games-minesweeper_2.2ubuntu3_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/d/debian-games/games-mud_2.2ubuntu3_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/d/debian-games/games-perl-dev_2.2ubuntu3_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/d/debian-games/games-platform_2.2ubuntu3_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/d/debian-games/games-programming_2.2ubuntu3_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/d/debian-games/games-puzzle_2.2ubuntu3_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/d/debian-games/games-python2-dev_2.2ubuntu3_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/d/debian-games/games-python3-dev_2.2ubuntu3_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/d/debian-games/games-racing_2.2ubuntu3_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/d/debian-games/games-rogue_2.2ubuntu3_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/d/debian-games/games-rpg_2.2ubuntu3_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/d/debian-games/games-shootemup_2.2ubuntu3_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/d/debian-games/games-simulation_2.2ubuntu3_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/d/debian-games/games-sport_2.2ubuntu3_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/d/debian-games/games-strategy_2.2ubuntu3_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/d/debian-games/games-tasks_2.2ubuntu3_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/d/debian-games/games-tetris_2.2ubuntu3_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/d/debian-games/games-toys_2.2ubuntu3_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/d/debian-games/games-typing_2.2ubuntu3_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/m/meta-gnome3/gnome-games_3.30+2_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/m/meta-kde/kdeedu_17.08.3+5.104ubuntu4_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/m/meta-kde/kdegames_17.08.3+5.104ubuntu4_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/m/meta-kde/kdegraphics_17.08.3+5.104ubuntu4_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/m/meta-kde/kdemultimedia_17.08.3+5.104ubuntu4_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/m/meta-kde/kdetoys_17.08.3+5.104ubuntu4_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/k/kicad/kicad-libraries_5.1.5+dfsg1-2build2_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/multiverse/u/ubuntu-restricted-addons/kubuntu-restricted-addons_26_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/multiverse/u/ubuntu-restricted-extras/kubuntu-restricted-extras_67_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/k/kubuntu-wallpapers/kubuntu-wallpapers_20.04.1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/o/openblas/libopenblas0_0.3.8+ds-1ubuntu0.20.04.1_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/multiverse/u/ubuntu-restricted-addons/lubuntu-restricted-addons_26_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/multiverse/u/ubuntu-restricted-extras/lubuntu-restricted-extras_67_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/l/lxqt-metapackages/lxqt_30_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/l/lxqt-metapackages/lxqt-core_30_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/d/debian-multimedia/multimedia-csound_0.8ubuntu1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/d/debian-multimedia/multimedia-supercollider_0.8ubuntu1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/q/qemu/qemu_4.2-3ubuntu6.18_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/s/supercollider-sc3-plugins/sc3-plugins_3.9.1~repack-3build1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/u/ubuntu-meta/ubuntu-desktop_1.450.2_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/u/ubuntu-meta/ubuntu-desktop-minimal_1.450.2_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/u/ubuntu-gnome-meta/ubuntu-gnome-desktop_0.87_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/u/ubuntu-gnome-wallpapers/ubuntu-gnome-wallpapers_16.10.4_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/u/ubuntu-mate-artwork/ubuntu-mate-artwork_20.04.2_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/u/ubuntu-mate-artwork/ubuntu-mate-wallpapers_20.04.2_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/u/ubuntu-packaging-guide/ubuntu-packaging-guide_1.0.2_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/multiverse/u/ubuntu-restricted-addons/ubuntu-restricted-addons_26_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/multiverse/u/ubuntu-restricted-extras/ubuntu-restricted-extras_67_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/u/ubuntu-wallpapers/ubuntu-wallpapers_20.04.2-0ubuntu1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/main/u/ubuntu-meta/ubuntu-wsl_1.450.2_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/u/ubuntukylin-wallpapers/ubuntukylin-wallpapers_20.04.2_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/u/ubuntustudio-meta/ubuntustudio-audio_0.210_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/u/ubuntustudio-meta/ubuntustudio-audio-core_0.210_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/u/ubuntustudio-meta/ubuntustudio-audio-plugins_0.210_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/u/ubuntustudio-meta/ubuntustudio-fonts_0.210_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/u/ubuntustudio-meta/ubuntustudio-graphics_0.210_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/u/ubuntustudio-meta/ubuntustudio-photography_0.210_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/u/ubuntustudio-meta/ubuntustudio-publishing_0.210_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/u/ubuntustudio-meta/ubuntustudio-video_0.210_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/multiverse/u/ubuntu-restricted-addons/xubuntu-restricted-addons_26_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/d/debichem/debichem-analytical-biochemistry_0.0.10_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/d/debichem/debichem-crystallography_0.0.10_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/d/debichem/debichem-development_0.0.10_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/d/debichem/debichem-input-generation-output-processing_0.0.10_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/d/debichem/debichem-molecular-abinitio_0.0.10_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/d/debichem/debichem-molecular-dynamics_0.0.10_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/d/debichem/debichem-periodic-abinitio_0.0.10_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/d/debian-junior/junior-games-adventure_1.29ubuntu1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/d/debian-junior/junior-games-arcade_1.29ubuntu1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/d/debian-junior/junior-games-puzzle_1.29ubuntu1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/d/debian-junior/junior-video_1.29ubuntu1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/f/ffmpeg/libavfilter-extra_4.2.4-1ubuntu0.1_amd64.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/d/debian-multimedia/multimedia-animation_0.8ubuntu1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/d/debian-multimedia/multimedia-audio-utilities_0.8ubuntu1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/d/debian-multimedia/multimedia-broadcasting_0.8ubuntu1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/d/debian-multimedia/multimedia-photography_0.8ubuntu1_all.deb
wget -c http://archive.ubuntu.com/ubuntu/pool/universe/d/debian-multimedia/multimedia-puredata_0.8ubuntu1_all.deb
