var alt_img = {
Korean:[
{name:"main_search.png", alt:"검색"},
{name:"home_gray_bt.png", alt:"메인 화면 보기"},
{name:"search_gray_bt.png", alt:"검색"},
{name:"but1.png", alt:"하위 목차 보기"},
{name:"list_icon.png", alt:"목차 화면 보기"},
{name:"text_small_icon.png", alt:"글자 축소"},
{name:"text_big_icon.png", alt:"글자 확대"},
{name:"swipe_left.png", alt:"이전 페이지 보기"},
{name:"swipe_right.png", alt:"다음 페이지 보기"},
{name:"image_size_icon.png", alt:"이미지 확대"},
{name:"close_bt.png", alt:"이전 페이지로 이동"}
],
English:[
{name:"main_search.png", alt:"Search"},
{name:"home_gray_bt.png", alt:"Start page"},
{name:"search_gray_bt.png", alt:"Search"},
{name:"but1.png", alt:"Subcontent"},
{name:"list_icon.png", alt:"Return to the table of contents"},
{name:"text_small_icon.png", alt:"Decrease font size"},
{name:"text_big_icon.png", alt:"Increase font size"},
{name:"swipe_left.png", alt:"Previous page"},
{name:"swipe_right.png", alt:"Next page"},
{name:"image_size_icon.png", alt:"Enlarge image"},
{name:"close_bt.png", alt:"Return to page"}
],
Albanian:[
{name:"main_search.png", alt:"Kërko"},
{name:"home_gray_bt.png", alt:"Faqja e fillimit"},
{name:"search_gray_bt.png", alt:"Kërko"},
{name:"but1.png", alt:"Nën-material"},
{name:"list_icon.png", alt:"Kthehu te tabela e përmbajtjes"},
{name:"text_small_icon.png", alt:"Zvogëlo masën e shkrimit"},
{name:"text_big_icon.png", alt:"Rrit masën e shkrimit"},
{name:"swipe_left.png", alt:"Faqja e mëparshme"},
{name:"swipe_right.png", alt:"Faqja tjetër"},
{name:"image_size_icon.png", alt:"Zmadho imazhin"},
{name:"close_bt.png", alt:"Kthehu te faqja"}
],
Arabic:[
{name:"main_search.png", alt:"البحث"},
{name:"home_gray_bt.png", alt:"صفحة البدء"},
{name:"search_gray_bt.png", alt:"البحث"},
{name:"but1.png", alt:"المحتوى الفرعي"},
{name:"list_icon.png", alt:"الرجوع إلى جدول المحتويات"},
{name:"text_small_icon.png", alt:"تقليل حجم الخط"},
{name:"text_big_icon.png", alt:"زيادة حجم الخط"},
{name:"swipe_left.png", alt:"الصفحة السابقة"},
{name:"swipe_right.png", alt:"الصفحة التالية"},
{name:"image_size_icon.png", alt:"تكبير الصورة"},
{name:"close_bt.png", alt:"الرجوع إلى الصفحة"}
],
Bulgarian:[
{name:"main_search.png", alt:"Търсене"},
{name:"home_gray_bt.png", alt:"Начална страница"},
{name:"search_gray_bt.png", alt:"Търсене"},
{name:"but1.png", alt:"Подраздели"},
{name:"list_icon.png", alt:"Връщане към съдържанието"},
{name:"text_small_icon.png", alt:"Намаляване размера на шрифта"},
{name:"text_big_icon.png", alt:"Увеличаване размера на шрифта"},
{name:"swipe_left.png", alt:"Предишна страница"},
{name:"swipe_right.png", alt:"Следваща страница"},
{name:"image_size_icon.png", alt:"Увеличаване на изображението"},
{name:"close_bt.png", alt:"Връщане към страница"}
],
Croatian:[
{name:"main_search.png", alt:"Traži"},
{name:"home_gray_bt.png", alt:"Početna stranica"},
{name:"search_gray_bt.png", alt:"Traži"},
{name:"but1.png", alt:"Podstavke sadržaja"},
{name:"list_icon.png", alt:"Povratak na sadržaj"},
{name:"text_small_icon.png", alt:"Povećanje veličine fonta"},
{name:"text_big_icon.png", alt:"Smanjenje veličine fonta"},
{name:"swipe_left.png", alt:"Prethodna stranica"},
{name:"swipe_right.png", alt:"Iduća stranica"},
{name:"image_size_icon.png", alt:"Povećanje slike"},
{name:"close_bt.png", alt:"Povratak na stranicu"}
],
Czech:[
{name:"main_search.png", alt:"Hledat"},
{name:"home_gray_bt.png", alt:"Výchozí stránka"},
{name:"search_gray_bt.png", alt:"Hledat"},
{name:"but1.png", alt:"Podobsah"},
{name:"list_icon.png", alt:"Návrat na obsah"},
{name:"text_small_icon.png", alt:"Zmenšit písmo"},
{name:"text_big_icon.png", alt:"Zvětšit písmo"},
{name:"swipe_left.png", alt:"Předchozí stránka"},
{name:"swipe_right.png", alt:"Další stránka"},
{name:"image_size_icon.png", alt:"Zvětšit obrázek"},
{name:"close_bt.png", alt:"Návrat na stránku"}
],
Danish:[
{name:"main_search.png", alt:"Søg"},
{name:"home_gray_bt.png", alt:"Siden Start"},
{name:"search_gray_bt.png", alt:"Søg"},
{name:"but1.png", alt:"Underindhold"},
{name:"list_icon.png", alt:"Tilbage til indholdsfortegnelsen"},
{name:"text_small_icon.png", alt:"Formindsk skriftstørrelse"},
{name:"text_big_icon.png", alt:"Forøg skriftstørrelse"},
{name:"swipe_left.png", alt:"Forrige side"},
{name:"swipe_right.png", alt:"Næste side"},
{name:"image_size_icon.png", alt:"Forstør billede"},
{name:"close_bt.png", alt:"Tilbage til side"}
],
Dutch:[
{name:"main_search.png", alt:"Zoeken"},
{name:"home_gray_bt.png", alt:"Startpagina"},
{name:"search_gray_bt.png", alt:"Zoeken"},
{name:"but1.png", alt:"Subinhoud"},
{name:"list_icon.png", alt:"Terug naar de inhoudsopgave"},
{name:"text_small_icon.png", alt:"Lettertype verkleinen"},
{name:"text_big_icon.png", alt:"Lettertype vergroten"},
{name:"swipe_left.png", alt:"Vorige pagina"},
{name:"swipe_right.png", alt:"Volgende pagina"},
{name:"image_size_icon.png", alt:"Afbeelding vergroten"},
{name:"close_bt.png", alt:"Terug naar pagina"}
],
Estonian:[
{name:"main_search.png", alt:"Otsing"},
{name:"home_gray_bt.png", alt:"Avaleht"},
{name:"search_gray_bt.png", alt:"Otsing"},
{name:"but1.png", alt:"Alamsisu"},
{name:"list_icon.png", alt:"Mine tagasi sisukorda"},
{name:"text_small_icon.png", alt:"Vähenda kirja"},
{name:"text_big_icon.png", alt:"Suurenda kirja"},
{name:"swipe_left.png", alt:"Eelmine leht"},
{name:"swipe_right.png", alt:"Järgmine leht"},
{name:"image_size_icon.png", alt:"Suurenda pilti"},
{name:"close_bt.png", alt:"Mine tagasi lehele"}
],
Farsi:[
{name:"main_search.png", alt:"جستجو"},
{name:"home_gray_bt.png", alt:"صفحه نخست"},
{name:"search_gray_bt.png", alt:"جستجو"},
{name:"but1.png", alt:"زیر محتوا"},
{name:"list_icon.png", alt:"بازگشت به فهرست مطالب"},
{name:"text_small_icon.png", alt:"کوچک نمودن اندازه قلم"},
{name:"text_big_icon.png", alt:"بزرگ نمودن اندازه قلم"},
{name:"swipe_left.png", alt:"صفحه قبلی"},
{name:"swipe_right.png", alt:"صفحه بعدی"},
{name:"image_size_icon.png", alt:"بزرگنمایی تصویر"},
{name:"close_bt.png", alt:"بازگشت به صفحه"}
],
Finnish:[
{name:"main_search.png", alt:"Haku"},
{name:"home_gray_bt.png", alt:"Aloitussivu"},
{name:"search_gray_bt.png", alt:"Haku"},
{name:"but1.png", alt:"Alisisältö"},
{name:"list_icon.png", alt:"Palaa sisällysluetteloon"},
{name:"text_small_icon.png", alt:"Pienennä fonttikokoa"},
{name:"text_big_icon.png", alt:"Suurenna fonttikokoa"},
{name:"swipe_left.png", alt:"Edellinen sivu"},
{name:"swipe_right.png", alt:"Seuraava sivu"},
{name:"image_size_icon.png", alt:"Suurenna kuvaa"},
{name:"close_bt.png", alt:"Palaa sivulle"}
],
French:[
{name:"main_search.png", alt:"Recherche"},
{name:"home_gray_bt.png", alt:"Page de démarrage"},
{name:"search_gray_bt.png", alt:"Recherche"},
{name:"but1.png", alt:"Section"},
{name:"list_icon.png", alt:"Revenir à la table des matières"},
{name:"text_small_icon.png", alt:"Réduire la taille de la police"},
{name:"text_big_icon.png", alt:"Augmenter la taille de la police"},
{name:"swipe_left.png", alt:"Page précédente"},
{name:"swipe_right.png", alt:"Page suivante"},
{name:"image_size_icon.png", alt:"Agrandir l’image"},
{name:"close_bt.png", alt:"Revenir à la page"}
],
French_CA:[

],
German:[
{name:"main_search.png", alt:"Suche"},
{name:"home_gray_bt.png", alt:"Startseite"},
{name:"search_gray_bt.png", alt:"Suche"},
{name:"but1.png", alt:"Untergeordneter Inhalt"},
{name:"list_icon.png", alt:"Zurück zum Inhaltsverzeichnis"},
{name:"text_small_icon.png", alt:"Schriftart verkleinern"},
{name:"text_big_icon.png", alt:"Schriftart vergrößern"},
{name:"swipe_left.png", alt:"Vorherige Seite"},
{name:"swipe_right.png", alt:"Nächste Seite"},
{name:"image_size_icon.png", alt:"Bild vergrößern"},
{name:"close_bt.png", alt:"Zurück zur Seite"}
],
Greek:[
{name:"main_search.png", alt:"Αναζήτηση"},
{name:"home_gray_bt.png", alt:"Σελίδα έναρξης"},
{name:"search_gray_bt.png", alt:"Αναζήτηση"},
{name:"but1.png", alt:"Δευτερεύον περιεχόμενο"},
{name:"list_icon.png", alt:"Επιστροφή στον πίνακα περιεχομένων"},
{name:"text_small_icon.png", alt:"Μείωση του μεγέθους γραμματοσειράς"},
{name:"text_big_icon.png", alt:"Αύξηση του μεγέθους γραμματοσειράς"},
{name:"swipe_left.png", alt:"Προηγούμενη σελίδα"},
{name:"swipe_right.png", alt:"Επόμενη σελίδα"},
{name:"image_size_icon.png", alt:"Μεγέθυνση εικόνας"},
{name:"close_bt.png", alt:"Επιστροφή στη σελίδα"}
],
HongKong:[
{name:"main_search.png", alt:"搜尋"},
{name:"home_gray_bt.png", alt:"開始頁面"},
{name:"search_gray_bt.png", alt:"搜尋"},
{name:"but1.png", alt:"子目錄"},
{name:"list_icon.png", alt:"返回目錄"},
{name:"text_small_icon.png", alt:"減小字體大小"},
{name:"text_big_icon.png", alt:"增加字體大小"},
{name:"swipe_left.png", alt:"上一頁"},
{name:"swipe_right.png", alt:"下一頁"},
{name:"image_size_icon.png", alt:"放大圖像"},
{name:"close_bt.png", alt:"返回頁面"}
],
Hungarian:[
{name:"main_search.png", alt:"Keresés"},
{name:"home_gray_bt.png", alt:"Kezdőlap"},
{name:"search_gray_bt.png", alt:"Keresés"},
{name:"but1.png", alt:"Altartalom"},
{name:"list_icon.png", alt:"Vissza a tartalomjegyzékhez"},
{name:"text_small_icon.png", alt:"Betűméret csökkentése"},
{name:"text_big_icon.png", alt:"Betűméret növelése"},
{name:"swipe_left.png", alt:"Előző oldal"},
{name:"swipe_right.png", alt:"Következő oldal"},
{name:"image_size_icon.png", alt:"Kép nagyítása"},
{name:"close_bt.png", alt:"Vissza az oldalra"}
],
Indonesian:[
{name:"main_search.png", alt:"Cari"},
{name:"home_gray_bt.png", alt:"Halaman awal"},
{name:"search_gray_bt.png", alt:"Cari"},
{name:"but1.png", alt:"Subkonten"},
{name:"list_icon.png", alt:"Kembali ke daftar isi"},
{name:"text_small_icon.png", alt:"Perkecil ukuran huruf"},
{name:"text_big_icon.png", alt:"Perbesar ukuran huruf"},
{name:"swipe_left.png", alt:"Halaman sebelumnya"},
{name:"swipe_right.png", alt:"Halaman berikutnya"},
{name:"image_size_icon.png", alt:"Besarkan gambar"},
{name:"close_bt.png", alt:"Kembali ke halaman"}
],
Italian:[
{name:"main_search.png", alt:"Ricerca"},
{name:"home_gray_bt.png", alt:"Pagina iniziale"},
{name:"search_gray_bt.png", alt:"Ricerca"},
{name:"but1.png", alt:"Sotto-contenuti"},
{name:"list_icon.png", alt:"Torna al sommario"},
{name:"text_small_icon.png", alt:"Diminuisci dimensione carattere"},
{name:"text_big_icon.png", alt:"Aumenta dimensione carattere"},
{name:"swipe_left.png", alt:"Pagina precedente"},
{name:"swipe_right.png", alt:"Pagina successiva"},
{name:"image_size_icon.png", alt:"Ingrandisci immagine"},
{name:"close_bt.png", alt:"Torna alla pagina"}
],
Kazakh:[
{name:"main_search.png", alt:"Іздеу"},
{name:"home_gray_bt.png", alt:"«Бастау» беті"},
{name:"search_gray_bt.png", alt:"Іздеу"},
{name:"but1.png", alt:"Ішкі мазмұн"},
{name:"list_icon.png", alt:"Мазмұнға оралу"},
{name:"text_small_icon.png", alt:"Қаріп өлшемін кішірейту"},
{name:"text_big_icon.png", alt:"Қаріп өлшемін үлкейту"},
{name:"swipe_left.png", alt:"Алдыңғы бет"},
{name:"swipe_right.png", alt:"Келесі бет"},
{name:"image_size_icon.png", alt:"Кескінді үлкейту"},
{name:"close_bt.png", alt:"Бетке оралу"}
],
Latvian:[
{name:"main_search.png", alt:"Meklēšana"},
{name:"home_gray_bt.png", alt:"Sākuma lapa"},
{name:"search_gray_bt.png", alt:"Meklēšana"},
{name:"but1.png", alt:"Apakšsaturs"},
{name:"list_icon.png", alt:"Atgriezties uz satura rādītāju"},
{name:"text_small_icon.png", alt:"Samazināt fonta izmēru"},
{name:"text_big_icon.png", alt:"Palielināt fonta izmēru"},
{name:"swipe_left.png", alt:"Iepriekšējā lapa"},
{name:"swipe_right.png", alt:"Nākamā lapa"},
{name:"image_size_icon.png", alt:"Palielināt attēlu"},
{name:"close_bt.png", alt:"Atgriezties uz lapu"}
],
Lithuanian:[
{name:"main_search.png", alt:"Paieška"},
{name:"home_gray_bt.png", alt:"Pradžios puslapis"},
{name:"search_gray_bt.png", alt:"Paieška"},
{name:"but1.png", alt:"Poskyris"},
{name:"list_icon.png", alt:"Grįžti į turinį"},
{name:"text_small_icon.png", alt:"Sumažinti šriftą"},
{name:"text_big_icon.png", alt:"Padidinti šriftą"},
{name:"swipe_left.png", alt:"Ankstesnis puslapis"},
{name:"swipe_right.png", alt:"Kitas puslapis"},
{name:"image_size_icon.png", alt:"Padidinti vaizdą"},
{name:"close_bt.png", alt:"Grįžti į puslapį"}
],
Macedonian:[
{name:"main_search.png", alt:"Пребарај"},
{name:"home_gray_bt.png", alt:"Почетна страница"},
{name:"search_gray_bt.png", alt:"Пребарај"},
{name:"but1.png", alt:"Подсодржина"},
{name:"list_icon.png", alt:"Врати се во содржина"},
{name:"text_small_icon.png", alt:"Намали големина на фонт"},
{name:"text_big_icon.png", alt:"Зголеми големина на фонт"},
{name:"swipe_left.png", alt:"Претходна страница"},
{name:"swipe_right.png", alt:"Следна страница"},
{name:"image_size_icon.png", alt:"Зголеми слика"},
{name:"close_bt.png", alt:"Врати се на страница"}
],
Norwegian:[
{name:"main_search.png", alt:"Søk"},
{name:"home_gray_bt.png", alt:"Startside"},
{name:"search_gray_bt.png", alt:"Søk"},
{name:"but1.png", alt:"Underinnhold"},
{name:"list_icon.png", alt:"Gå tilbake til innholdsfortegnelsen"},
{name:"text_small_icon.png", alt:"Reduser skriftstørrelsen"},
{name:"text_big_icon.png", alt:"Øk skriftstørrelsen"},
{name:"swipe_left.png", alt:"Forrige side"},
{name:"swipe_right.png", alt:"Neste side"},
{name:"image_size_icon.png", alt:"Forstørr bilde"},
{name:"close_bt.png", alt:"Gå tilbake til side"}
],
Polish:[
{name:"main_search.png", alt:"Wyszukiwanie"},
{name:"home_gray_bt.png", alt:"Strona startowa"},
{name:"search_gray_bt.png", alt:"Wyszukiwanie"},
{name:"but1.png", alt:"Zawartość podrzędna"},
{name:"list_icon.png", alt:"Powróć do spisu treści"},
{name:"text_small_icon.png", alt:"Zmniejsz rozmiar czcionki"},
{name:"text_big_icon.png", alt:"Zwiększ rozmiar czcionki"},
{name:"swipe_left.png", alt:"Poprzednia strona"},
{name:"swipe_right.png", alt:"Następna strona"},
{name:"image_size_icon.png", alt:"Powiększ obraz"},
{name:"close_bt.png", alt:"Powróć do strony"}
],
Portuguese:[
{name:"main_search.png", alt:"Procurar"},
{name:"home_gray_bt.png", alt:"Página inicial"},
{name:"search_gray_bt.png", alt:"Procurar"},
{name:"but1.png", alt:"Sub-conteúdo"},
{name:"list_icon.png", alt:"Voltar para o índice"},
{name:"text_small_icon.png", alt:"Diminuir o tamanho da letra"},
{name:"text_big_icon.png", alt:"Aumentar o tamanho da letra"},
{name:"swipe_left.png", alt:"Página anterior"},
{name:"swipe_right.png", alt:"Página seguinte"},
{name:"image_size_icon.png", alt:"Ampliar imagem"},
{name:"close_bt.png", alt:"Voltar para a página"}
],
Portuguese_BR:[
{name:"swipe_left.png", alt:"Página anterior"},
{name:"swipe_right.png", alt:"Página seguinte"}
],
PRC_Chinese:[
{name:"main_search.png", alt:"搜索"},
{name:"home_gray_bt.png", alt:"开始页面"},
{name:"search_gray_bt.png", alt:"搜索"},
{name:"but1.png", alt:"子目录"},
{name:"list_icon.png", alt:"返回目录"},
{name:"text_small_icon.png", alt:"减小字体大小"},
{name:"text_big_icon.png", alt:"增大字体大小"},
{name:"swipe_left.png", alt:"上一页"},
{name:"swipe_right.png", alt:"下一页"},
{name:"image_size_icon.png", alt:"放大图像"},
{name:"close_bt.png", alt:"返回页面"}
],
Romanian:[
{name:"main_search.png", alt:"Căutare"},
{name:"home_gray_bt.png", alt:"Pagină de pornire"},
{name:"search_gray_bt.png", alt:"Căutare"},
{name:"but1.png", alt:"Subconţinut"},
{name:"list_icon.png", alt:"Revenire la cuprins"},
{name:"text_small_icon.png", alt:"Micşorarea dimensiunii fontului"},
{name:"text_big_icon.png", alt:"Mărirea dimensiunii fontului"},
{name:"swipe_left.png", alt:"Pagină precedentă"},
{name:"swipe_right.png", alt:"Pagina următoare"},
{name:"image_size_icon.png", alt:"Mărire imagine"},
{name:"close_bt.png", alt:"Revenire la pagină"}
],
Russian:[
{name:"main_search.png", alt:"Поиск"},
{name:"home_gray_bt.png", alt:"Начальная страница"},
{name:"search_gray_bt.png", alt:"Поиск"},
{name:"but1.png", alt:"Дополнительное содержимое"},
{name:"list_icon.png", alt:"Возврат к содержанию"},
{name:"text_small_icon.png", alt:"Уменьшить размер шрифта"},
{name:"text_big_icon.png", alt:"Увеличить размер шрифта"},
{name:"swipe_left.png", alt:"Предыдущая страница"},
{name:"swipe_right.png", alt:"Следующая страница"},
{name:"image_size_icon.png", alt:"Увеличить изображение"},
{name:"close_bt.png", alt:"Возврат к странице"}
],
Serbian:[
{name:"main_search.png", alt:"Pretraga"},
{name:"home_gray_bt.png", alt:"Početna stranica"},
{name:"search_gray_bt.png", alt:"Pretraga"},
{name:"but1.png", alt:"Pod-sadržaj"},
{name:"list_icon.png", alt:"Vrati se na sadržaj"},
{name:"text_small_icon.png", alt:"Smanji veličinu fonta"},
{name:"text_big_icon.png", alt:"Povećaj veličinu fonta"},
{name:"swipe_left.png", alt:"Prethodna strana"},
{name:"swipe_right.png", alt:"Sledeća strana"},
{name:"image_size_icon.png", alt:"Uvećaj sliku"},
{name:"close_bt.png", alt:"Vrati na stranicu"}
],
Singapore_Chinese:[
{name:"main_search.png", alt:"搜索"},
{name:"home_gray_bt.png", alt:"开始页面"},
{name:"search_gray_bt.png", alt:"搜索"},
{name:"but1.png", alt:"子目录"},
{name:"list_icon.png", alt:"返回目录"},
{name:"text_small_icon.png", alt:"减小字体大小"},
{name:"text_big_icon.png", alt:"增大字体大小"},
{name:"swipe_left.png", alt:"上一页"},
{name:"swipe_right.png", alt:"下一页"},
{name:"image_size_icon.png", alt:"放大图像"},
{name:"close_bt.png", alt:"返回页面"}
],
Slovak:[
{name:"main_search.png", alt:"Vyhľadávanie"},
{name:"home_gray_bt.png", alt:"Úvodná stránka"},
{name:"search_gray_bt.png", alt:"Vyhľadávanie"},
{name:"but1.png", alt:"Doplnok k obsahu"},
{name:"list_icon.png", alt:"Späť na obsah"},
{name:"text_small_icon.png", alt:"Zmenšiť veľkosť písma"},
{name:"text_big_icon.png", alt:"Zväčšiť veľkosť písma"},
{name:"swipe_left.png", alt:"Predchádzajúca strana"},
{name:"swipe_right.png", alt:"Nasledujúca strana"},
{name:"image_size_icon.png", alt:"Zväčšiť obraz"},
{name:"close_bt.png", alt:"Späť na stránku"}
],
Slovenian:[
{name:"main_search.png", alt:"Iskanje"},
{name:"home_gray_bt.png", alt:"Začetna stran"},
{name:"search_gray_bt.png", alt:"Iskanje"},
{name:"but1.png", alt:"Podvsebina"},
{name:"list_icon.png", alt:"Vrni se na kazalo"},
{name:"text_small_icon.png", alt:"Zmanjšaj velikost pisave"},
{name:"text_big_icon.png", alt:"Povečaj velikost pisave"},
{name:"swipe_left.png", alt:"Prejšnja stran"},
{name:"swipe_right.png", alt:"Naslednja stran"},
{name:"image_size_icon.png", alt:"Povečaj sliko"},
{name:"close_bt.png", alt:"Vrni se na stran"}
],
Spanish:[
{name:"main_search.png", alt:"Buscar"},
{name:"home_gray_bt.png", alt:"Página de inicio"},
{name:"search_gray_bt.png", alt:"Buscar"},
{name:"but1.png", alt:"Subcontenido"},
{name:"list_icon.png", alt:"Volver al índice de contenidos"},
{name:"text_small_icon.png", alt:"Reducir tamaño de fuente"},
{name:"text_big_icon.png", alt:"Aumentar tamaño de fuente"},
{name:"swipe_left.png", alt:"Página anterior"},
{name:"swipe_right.png", alt:"Página siguiente"},
{name:"image_size_icon.png", alt:"Ampliar imagen"},
{name:"close_bt.png", alt:"Volver a la página"}
],
Spanish_LA:[
{name:"swipe_left.png", alt:"Página anterior"},
{name:"swipe_right.png", alt:"Página siguiente"}
],
Swedish:[
{name:"main_search.png", alt:"Sök"},
{name:"home_gray_bt.png", alt:"Startsida"},
{name:"search_gray_bt.png", alt:"Sök"},
{name:"but1.png", alt:"Sekundärt innehåll"},
{name:"list_icon.png", alt:"Gå tillbaka till innehållsförteckningen"},
{name:"text_small_icon.png", alt:"Minska teckenstorleken"},
{name:"text_big_icon.png", alt:"Öka teckenstorleken"},
{name:"swipe_left.png", alt:"Föregående sida"},
{name:"swipe_right.png", alt:"Nästa sida"},
{name:"image_size_icon.png", alt:"Förstora bilden"},
{name:"close_bt.png", alt:"Gå tillbaka till sidan"}
],
Taiwan:[
{name:"main_search.png", alt:"搜尋"},
{name:"home_gray_bt.png", alt:"開始頁"},
{name:"search_gray_bt.png", alt:"搜尋"},
{name:"but1.png", alt:"子目錄"},
{name:"list_icon.png", alt:"返回至目次"},
{name:"text_small_icon.png", alt:"縮小字型大小"},
{name:"text_big_icon.png", alt:"增加字型大小"},
{name:"swipe_left.png", alt:"上一頁"},
{name:"swipe_right.png", alt:"下一頁"},
{name:"image_size_icon.png", alt:"放大影像"},
{name:"close_bt.png", alt:"返回至頁面"}
],
Thai:[
{name:"main_search.png", alt:"การค้นหา"},
{name:"home_gray_bt.png", alt:"หน้าเริ่มต้น"},
{name:"search_gray_bt.png", alt:"การค้นหา"},
{name:"but1.png", alt:"เนื้อหาย่อย"},
{name:"list_icon.png", alt:"กลับไปยังสารบัญ"},
{name:"text_small_icon.png", alt:"ลดขนาดแบบอักษร"},
{name:"text_big_icon.png", alt:"เพิ่มขนาดแบบอักษร"},
{name:"swipe_left.png", alt:"หน้าก่อน"},
{name:"swipe_right.png", alt:"หน้าถัดไป"},
{name:"image_size_icon.png", alt:"ขยายภาพ"},
{name:"close_bt.png", alt:"กลับไปยังหน้า"}
],
Turkish:[
{name:"main_search.png", alt:"Arama"},
{name:"home_gray_bt.png", alt:"Başlangıç sayfası"},
{name:"search_gray_bt.png", alt:"Arama"},
{name:"but1.png", alt:"Alt içerik"},
{name:"list_icon.png", alt:"İçindekilere geri dön"},
{name:"text_small_icon.png", alt:"Yazı boyutunu azalt"},
{name:"text_big_icon.png", alt:"Yazı boyutunu artır"},
{name:"swipe_left.png", alt:"Önceki sayfa"},
{name:"swipe_right.png", alt:"Sonraki sayfa"},
{name:"image_size_icon.png", alt:"Görüntüyü büyüt"},
{name:"close_bt.png", alt:"Sayfaya geri dön"}
],
Ukrainian:[
{name:"main_search.png", alt:"Пошук"},
{name:"home_gray_bt.png", alt:"Початкова сторінка"},
{name:"search_gray_bt.png", alt:"Пошук"},
{name:"but1.png", alt:"Додатковий вміст"},
{name:"list_icon.png", alt:"Повернутися до змісту"},
{name:"text_small_icon.png", alt:"Зменшити розмір шрифту"},
{name:"text_big_icon.png", alt:"Збільшити розмір шрифту"},
{name:"swipe_left.png", alt:"Попередня сторінка"},
{name:"swipe_right.png", alt:"Наступна сторінка"},
{name:"image_size_icon.png", alt:"Збільшити зображення"},
{name:"close_bt.png", alt:"Повернутися до сторінки"}
],
Urdu:[
{name:"main_search.png", alt:"تلاش"},
{name:"home_gray_bt.png", alt:"صفحہ شروع کریں"},
{name:"search_gray_bt.png", alt:"تلاش"},
{name:"but1.png", alt:"ذیلی مواد"},
{name:"list_icon.png", alt:"مواد کے ٹیبل پر واپس جائیں"},
{name:"text_small_icon.png", alt:"فونٹ سائز کم کریں"},
{name:"text_big_icon.png", alt:"فونٹ سائز بڑھائیں"},
{name:"swipe_left.png", alt:"سابقہ صفحہ"},
{name:"swipe_right.png", alt:"اگلا صفحۃ"},
{name:"image_size_icon.png", alt:"تصویر بڑی کریں"},
{name:"close_bt.png", alt:"صفحہ پر واپس جائیں"}
],
Uzbek:[
{name:"main_search.png", alt:"Qidirish"},
{name:"home_gray_bt.png", alt:"Boshlash sahifasi"},
{name:"search_gray_bt.png", alt:"Qidirish"},
{name:"but1.png", alt:"Tagtarkib"},
{name:"list_icon.png", alt:"Mundarijaga qaytish"},
{name:"text_small_icon.png", alt:"Shrift o‘lchamini kichraytirish"},
{name:"text_big_icon.png", alt:"Shrift o‘lchamini kattalashtirish"},
{name:"swipe_left.png", alt:"Avvalgi sahifa"},
{name:"swipe_right.png", alt:"Keyingi sahifa"},
{name:"image_size_icon.png", alt:"Tasvirni kattalashtirish"},
{name:"close_bt.png", alt:"Sahifaga qaytish"}
],
Vietnamese:[
{name:"main_search.png", alt:"Tìm kiếm"},
{name:"home_gray_bt.png", alt:"Trang bắt đầu"},
{name:"search_gray_bt.png", alt:"Tìm kiếm"},
{name:"but1.png", alt:"Nội dung phụ"},
{name:"list_icon.png", alt:"Quay lại mục lục"},
{name:"text_small_icon.png", alt:"Giảm kích thước phông chữ"},
{name:"text_big_icon.png", alt:"Tăng kích thước phông chữ"},
{name:"swipe_left.png", alt:"Trang trước"},
{name:"swipe_right.png", alt:"Trang tiếp"},
{name:"image_size_icon.png", alt:"Phóng to hình ảnh"},
{name:"close_bt.png", alt:"Quay lại trang"}
],
Hebrew:[
{name:"main_search.png", alt:"חיפוש"},
{name:"home_gray_bt.png", alt:"עמוד התחלה"},
{name:"search_gray_bt.png", alt:"חיפוש"},
{name:"but1.png", alt:"תוכן משנה"},
{name:"list_icon.png", alt:"בחזרה לתוכן עניינים"},
{name:"text_small_icon.png", alt:"הקטן גודל פונט"},
{name:"text_big_icon.png", alt:"הגדל גודל פונט"},
{name:"swipe_left.png", alt:"דף קודם"},
{name:"swipe_right.png", alt:"הדף הבא"},
{name:"image_size_icon.png", alt:"הגדל תמונה"},
{name:"close_bt.png", alt:"חזרה לעמוד"}
],
Japanese:[

]
};