var model_all = "SM-A320FL<br/>SM-A520F"
var message = {
"Korean":{
title: "사용 설명서",
model: model_all,
search: "검색",
home: "홈",
list: "목차",
settings: "설정",
font_tit: "글자 크기",
line_tit: "줄 간격",
view_toc3: "핵심 기능 보기",
toc_bottom: "일부 내용은 제품의 버전에 따라 다를 수 있으며 예고 없이 변경될 수 있습니다.",
keyword: "검색어 입력",
recent_key: "최근 검색어",
result: "검색 결과 없음",
expand: "더보기",
collapse: "숨기기",
result_toc: "목차 검색",
search_short: "검색 단어가 너무 짧습니다.",
search_more: "더보기",
search_less: "숨기기",
bookmark: "자주 찾아보는 내용은 북마크에 추가해 편리하게 이용할 수 있습니다.<br />북마크를 추가할 페이지에서, 화면 하단의 <img src='../contents/images/template/bookmark_off.png' class='book_icon' /> 누르세요. 해당 내용이 북마크에 추가됩니다.<br /><br /><div id='book_area'><img src='../contents/images/template/bookmark_info.png' class='book_info' /></div>",
close: "닫기",
bookmark_tit: "북마크",
basic_tit: "기본 기능",
application_tit: "애플리케이션",
setting_tit: "설정",
recom_tit: "추천 기능",
privacy_tit: "개인정보 보호 및 안전",
connect_tit: "연결",
setting_tit1: "연결",
setting_tit2: "디바이스",
setting_tit3: "개인",
setting_tit4: "시스템",
intro: "소개",
bookmark_over: "북마크는 최대 20개까지만 등록할 수 있습니다."
},
"English":{
title: "User Manual",
model: model_all,
search: "Search",
home: "Home",
list: "List",
settings: "Settings",
font_tit: "Font size",
line_tit: "Line spacing",
view_toc3: "Key Features",
toc_bottom: "Some content on your device may differ or change without notice.",
keyword: "Enter search keyword",
recent_key: "Recent keywords",
result: "No results found.",
expand: "Expand",
collapse: "Collapse",
result_toc: "Table of contents",
search_short: "Keyword is too short.",
search_more: "More",
search_less: "Less",
bookmark: "Bookmark pages that you frequently view to get quick access.<br />To bookmark a page, tap <img src='../contents/images/template/bookmark_off.png' class='book_icon' /> at the bottom of the screen. The page will be added to your bookmarks list.<br /><br /><div id='book_area'><img src='../contents/images/template/bookmark_info.png' class='book_info' /></div>",
close: "Close",
bookmark_tit: "Bookmarks",
basic_tit: "Basics",
application_tit: "Applications",
setting_tit: "Settings",
recom_tit: "Recommended",
privacy_tit: "Privacy and safety",
connect_tit: "Connectivity",
setting_tit1: " ",
setting_tit2: " ",
setting_tit3: " ",
setting_tit4: " ",
intro: "Introduction",
bookmark_over: "You can add up to 20 pages to the bookmarks list."
},
"Arabic":{
title: "دليل المستخدم",
model: model_all,
search: "بحث",
home: "صفحة البدء",
list: "القائمة",
settings: "الضبط",
font_tit: "حجم الخط",
line_tit: "تباعد الأسطر",
view_toc3: "الميزات الرئيسية",
toc_bottom: "بعض المحتوى الموجود على جهازك قد يختلف أو يتغير بدون إشعار.",
keyword: "إدخال كلمة أساسية للبحث",
recent_key: "كلمات البحث الأساسية الأخيرة",
result: "لم يتم العثور على نتائج.",
expand: "توسيع",
collapse: "طي",
result_toc: "جدول المحتويات",
search_short: "الكلمة الأساسية قصيرة للغاية.",
search_more: "المزيد",
search_less: "أقل",
bookmark: "صفحات العلامات المرجعية التي تشاهدها من حين إلى آخر للوصول السريع.<br />لوضع علامة مرجعية على صفحة، اضغط على <img src='../contents/images/template/bookmark_off.png' class='book_icon' /> في الجزء السفلي من الشاشة. يتم إضافة الصورة إلى قائمة العلامات المرجعية.<br /><br /><div id='book_area'><img src='../contents/images/template/bookmark_info.png' class='book_info' /></div>",
close: "إغلاق",
bookmark_tit: "العلامات المرجعية",
basic_tit: "الأساسيات",
application_tit: "التطبيقات",
setting_tit: "الضبط",
recom_tit: "موصى به",
privacy_tit: "الخصوصية والسلامة",
connect_tit: "القابلية للتوصيل",
setting_tit1: "الاتصالات",
setting_tit2: "الجھاز",
setting_tit3: "شخصي",
setting_tit4: "النظام",
intro: "مقدمة",
bookmark_over: "مكنك إضافة ما يصل إلى 20 صفحة إلى قائمة العلامات المرجعية."
},
"Bulgarian":{
title: "Ръководство на потребителя",
model: model_all,
search: "Търсене",
home: "Нач.",
list: "Списък",
settings: "Настройки",
font_tit: "Размер на шрифта",
line_tit: "Междуредово разстояние",
view_toc3: "Ключови функции",
toc_bottom: "Част от съдържанието на вашето устройство може да е различно или да бъде променено без предизвестие.",
keyword: "Въведете ключова дума за търсене",
recent_key: "Скорошни ключови думи",
result: "Не са намерени резултати.",
expand: "Разш.",
collapse: "Свив.",
result_toc: "Съдържание",
search_short: "Ключовата дума е твърде къса.",
search_more: "Още",
search_less: "По-малко",
bookmark: "Маркира страници, които гледате често, за да получите бърз достъп.<br />За да маркирате страница, чукнете <img src='../contents/images/template/bookmark_off.png' class='book_icon' /> в долната част на екрана. Страницата ще бъде добавена към списъка с показалци.<br /><br /><div id='book_area'><img src='../contents/images/template/bookmark_info.png' class='book_info' /></div>",
close: "Затваряне",
bookmark_tit: "Показалци",
basic_tit: "Основни функции",
application_tit: "Приложения",
setting_tit: "Настройки",
recom_tit: "Препоръчани",
privacy_tit: "Поверителност и безопасност",
connect_tit: "Свързване",
setting_tit1: "Връзки",
setting_tit2: "Устройство",
setting_tit3: "Персонално",
setting_tit4: "Системен",
intro: "Увод",
bookmark_over: "Можете да добавите до 20 страници към списъка с показалци."
},
"Croatian":{
title: "Korisnički priručnik",
model: model_all,
search: "Τraži",
home: "Početna",
list: "Popis",
settings: "Postavke",
font_tit: "Veličina slova",
line_tit: "Razmak između redova",
view_toc3: "Ključne značajke",
toc_bottom: "Neki se sadržaji na vašem uređaju mogu izmijeniti ili razlikovati bez prethodne obavijesti.",
keyword: "Unos ključne riječi za pretragu",
recent_key: "Nedavno upotrijebljene ključne riječi",
result: "Nema rezultata.",
expand: "det.",
collapse: "ukr.",
result_toc: "Sadržaj",
search_short: "Ključna riječ je prekratka.",
search_more: "Više",
search_less: "Manje",
bookmark: "Dodajte knjižne oznake na stranice koje često pregledavate za brzi pristup.<br />Za dodavanje knjižne oznake dodirnite <img src='../contents/images/template/bookmark_off.png' class='book_icon' /> na dnu zaslona. Stranica će biti dodana na popis knjižnih oznaka.<br /><br /><div id='book_area'><img src='../contents/images/template/bookmark_info.png' class='book_info' /></div>",
close: "Zatvoriti",
bookmark_tit: "Knjižne oznake",
basic_tit: "Osnovne funkcije",
application_tit: "Aplikacije",
setting_tit: "Postavke",
recom_tit: "Preporučeno",
privacy_tit: "Privatnost i sigurnost",
connect_tit: "Spajanje",
setting_tit1: "Veze",
setting_tit2: "Uređaj",
setting_tit3: "Osobno",
setting_tit4: "Sistem",
intro: "Uvod",
bookmark_over: "U popis knjižnih oznaka možete dodati do 20 stranica."
},
"Czech":{
title: "Uživatelská příručka",
model: model_all,
search: "Hledat",
home: "Domů",
list: "Seznam",
settings: "Nastavení",
font_tit: "Velikost písma",
line_tit: "Řádkování",
view_toc3: "Klíčové funkce",
toc_bottom: "Některý obsah ve vašem zařízení se může bez předchozího upozornění odlišit nebo změnit.",
keyword: "Zadat klíčové slovo pro vyhledávání",
recent_key: "Nedávná klíčová slova",
result: "Nenalezeny žádné výsledky.",
expand: "Rozb.",
collapse: "Sbal.",
result_toc: "Obsah",
search_short: "Klíčové slovo je příliš krátké.",
search_more: "Další",
search_less: "Méně",
bookmark: "Stránky, které často zobrazujete, lze uložit do záložek, což vám k nim zprostředkuje rychlý přístup.<br />Chcete-li stránku uložit do záložek, klepněte na položku <img src='../contents/images/template/bookmark_off.png' class='book_icon' /> ve spodní části obrazovky. Stránka se přidá do seznamu vašich záložek.<br /><br /><div id='book_area'><img src='../contents/images/template/bookmark_info.png' class='book_info' /></div>",
close: "Zavřít",
bookmark_tit: "Záložky",
basic_tit: "Základy",
application_tit: "Aplikace",
setting_tit: "Nastavení",
recom_tit: "Doporučeno",
privacy_tit: "Soukromí a bezpečnost",
connect_tit: "Konektivita",
setting_tit1: "Připojení",
setting_tit2: "Zařízení",
setting_tit3: "Osobní",
setting_tit4: "Systém",
intro: "Úvod",
bookmark_over: "Do seznamu záložek můžete přidat až 20 stránek."
},
"Danish":{
title: "Brugervejledning",
model: model_all,
search: "Søg",
home: "Startside",
list: "Liste",
settings: "Indstillinger",
font_tit: "Skriftstørrelse",
line_tit: "Linjeafstand",
view_toc3: "Hovedfunktioner",
toc_bottom: "Noget af indholdet på din enhed kan afvige eller blive ændret uden varsel.",
keyword: "Indtast søgenøgleord",
recent_key: "Nylige nøgleord",
result: "Ingen resultater blev fundet.",
expand: "Udvid",
collapse: "Skjul",
result_toc: "Indholdsoversigt",
search_short: "Nøgleord er for kort.",
search_more: "Mere",
search_less: "Mindre",
bookmark: "Bogmærkede sider, som du ofte bruger til at få hurtig adgang.<br />For at bogmærke en side, skal du trykke på <img src='../contents/images/template/bookmark_off.png' class='book_icon' /> nederst på skærmen. Siden bliver føjet til din liste over bogmærker.<br /><br /><div id='book_area'><img src='../contents/images/template/bookmark_info.png' class='book_info' /></div>",
close: "Luk",
bookmark_tit: "Bogmærker",
basic_tit: "Grundlæggende brug",
application_tit: "Applikationer",
setting_tit: "Indstillinger",
recom_tit: "Anbefalet",
privacy_tit: "Fortrolighed og sikkerhed",
connect_tit: "Tilslutning",
setting_tit1: "Forbindelse",
setting_tit2: "Enhed",
setting_tit3: "Personlig",
setting_tit4: "System",
intro: "Introduktion",
bookmark_over: "Du kan tilføje op til 20 sider til listen over bogmærker."
},
"Dutch":{
title: "Gebruiksaanwijzing",
model: model_all,
search: "Zoeken",
home: "Start",
list: "Lijst",
settings: "Instellingen",
font_tit: "Tekengrootte",
line_tit: "Regelafstand",
view_toc3: "Belangrijkste functies",
toc_bottom: "Bepaalde inhoud op uw apparaat kan afwijken of zonder kennisgeving worden gewijzigd.",
keyword: "Zoekwoord ingeven",
recent_key: "Recente zoekwoorden",
result: "Geen resultaten gevonden.",
expand: "Uitvwn",
collapse: "Samenvwn",
result_toc: "Inhoudsopgave",
search_short: "Zoekwoord is te kort.",
search_more: "Meer",
search_less: "Minder",
bookmark: "Stel pagina's die u regelmatig bekijkt, in als favorieten zodat u snel toegang kunt krijgen.<br />Als u een pagina wilt instellen als favoriet, tikt u op <img src='../contents/images/template/bookmark_off.png' class='book_icon' /> onder aan het scherm. De pagina wordt toegevoegd aan uw lijst met favorieten.<br /><br /><div id='book_area'><img src='../contents/images/template/bookmark_info.png' class='book_info' /></div>",
close: "Sluiten",
bookmark_tit: "Favorieten",
basic_tit: "Basisfuncties",
application_tit: "Applicaties",
setting_tit: "Instellingen",
recom_tit: "Aanbevolen",
privacy_tit: "Privacy en veiligheid",
connect_tit: "Connectiviteit",
setting_tit1: "Verbindingen",
setting_tit2: "Apparaat",
setting_tit3: "Persoonlijk",
setting_tit4: "Systeem",
intro: "Introductie",
bookmark_over: "U kunt maximaal 20 pagina's toevoegen aan de lijst met bladwijzers."
},
"Estonian":{
title: "Kasutusjuhend",
model: model_all,
search: "Otsi",
home: "Avaleht",
list: "Nimekiri",
settings: "Seaded",
font_tit: "Kirjasuurus",
line_tit: "Reavahe",
view_toc3: "Põhifunktsioonid",
toc_bottom: "Teatud seadmes olev sisu võib etteteatamiseta erineda või muutuda.",
keyword: "Sisestage otsingusõna",
recent_key: "Hiljutised otsingusõnad",
result: "Vasteid ei leitud.",
expand: "Laiend",
collapse: "Lühenda",
result_toc: "Sisukord",
search_short: "Otsingusõna on liiga lühike.",
search_more: "Veel",
search_less: "Vähem",
bookmark: "Lisake tihti külastatavad lehed järjehoidjatesse, et neile kiirelt ligi pääseda.<br />Lehe lisamiseks järjehoidjatesse toksake <img src='../contents/images/template/bookmark_off.png' class='book_icon' /> ekraani allosas. Leht lisatakse teie järjehoidjate nimekirja.<br /><br /><div id='book_area'><img src='../contents/images/template/bookmark_info.png' class='book_info' /></div>",
close: "Sulgege",
bookmark_tit: "Järjehoidjad",
basic_tit: "Põhiline",
application_tit: "Rakendused",
setting_tit: "Seaded",
recom_tit: "Soovitused",
privacy_tit: "Privaatsus ja turvalisus",
connect_tit: "Ühenduvus",
setting_tit1: "Ühendused",
setting_tit2: "Seade",
setting_tit3: "Isiklik",
setting_tit4: "Süsteem",
intro: "Sissejuhatus",
bookmark_over: "Saate järjehoidjate nimekirja lisada kuni 20 lehekülge."
},
"Farsi":{
title: "دفترچه راهنمای کاربر",
model: model_all,
search: "جستجو",
home: "خانه",
list: "لیست",
settings: "تنظیمات",
font_tit: "اندازه قلم",
line_tit: "فاصله بین خطوط",
view_toc3: "ویژگی‌های کلیدی",
toc_bottom: "برخی از محتوای روی دستگاه تان ممکن است متفاوت باشد یا بدون اعلام تغییر کند.",
keyword: "کلیدواژه برای جستجو را وارد کنید",
recent_key: "کلیدواژه های اخیر",
result: "نتیجه ای یافت نشد.",
expand: " مفصل",
collapse: " مختصر",
result_toc: "فهرست مطالب",
search_short: "کلیدواژه بیش از اندازه کوتاه است.",
search_more: "بیشتر",
search_less: "کمتر",
bookmark: "صفحه هایی که زیاد به آنها سر می زنید را برای دسترسی سریع به آنها نشانه گذاری کنید.<br />برای نشانه گذاری یک صفحه بر روی <img src='../contents/images/template/bookmark_off.png' class='book_icon' /> در پایین صفحه نمایش ضربه بزنید. صفحه به لیست نشانه گذاری های شما اضافه خواهد شد.<br /><br /><div id='book_area'><img src='../contents/images/template/bookmark_info.png' class='book_info' /></div>",
close: "بستن",
bookmark_tit: "نشانه ها",
basic_tit: "مقدمات",
application_tit: "برنامه های کاربردی",
setting_tit: "تنظیمات",
recom_tit: "پیشنهاد شده",
privacy_tit: "حریم خصوصی و امنیت",
connect_tit: "اتصال‏",
setting_tit1: "اتصالات",
setting_tit2: "دستگاہ",
setting_tit3: "شخصی",
setting_tit4: "سیستم",
intro: "معرفی",
bookmark_over: "می توانید تا 20 صفحه را به لیست نشانه گذاری ها اضافه کنید."
},
"Finnish":{
title: "Käyttöopas",
model: model_all,
search: "Etsi",
home: "Koti",
list: "Luett",
settings: "Asetukset",
font_tit: "Fonttikoko",
line_tit: "Riviväli",
view_toc3: "Tärkeimmät ominaisuudet",
toc_bottom: "Osa laitteen sisällöstä voi poiketa tässä esitetystä, tai sisältöä voidaan muuttaa ilman ennakkoilmoitusta.",
keyword: "Anna hakusana",
recent_key: "Viime hakusanat",
result: "Tuloksia ei löytynyt.",
expand: "Laaj.",
collapse: "Tiiv.",
result_toc: "Sisällysluettelo",
search_short: "Hakusana on liian lyhyt.",
search_more: "Lisää",
search_less: "Vähemmän",
bookmark: "Voit käyttää usein tarvitsemiasi sivuja nopeasti lisäämällä niihin kirjanmerkin.<br />Voit lisätä sivulle kirjanmerkin napauttamalla <img src='../contents/images/template/bookmark_off.png' class='book_icon' /> näytön alareunassa. Sivu lisätään kirjanmerkkiluetteloon.<br /><br /><div id='book_area'><img src='../contents/images/template/bookmark_info.png' class='book_info' /></div>",
close: "Sulje",
bookmark_tit: "Kirjanmerkit",
basic_tit: "Perustoiminnot",
application_tit: "Sovellukset",
setting_tit: "Asetukset",
recom_tit: "Suositeltu",
privacy_tit: "Yksityisyys ja turvallisuus",
connect_tit: "Liitettävyys",
setting_tit1: "Yhteydet",
setting_tit2: "Laite",
setting_tit3: "Henkilökohtainen",
setting_tit4: "Järjestelmä",
intro: "Esittely",
bookmark_over: "Voit lisätä enintään 20 sivua kirjanmerkkiluetteloon."
},
"French":{
title: "Mode d’emploi",
model: model_all,
search: "Rech.",
home: "Accueil",
list: "Liste",
settings: "Paramètres",
font_tit: "Taille de police",
line_tit: "Interligne",
view_toc3: "Principales fonctionnalités",
toc_bottom: "Certains contenus de votre appareil peuvent différer ou être modifiés sans préavis.",
keyword: "Saisir le mot clé de recherche",
recent_key: "Mots clés récents",
result: "Aucun résultat trouvé.",
expand: "Affich.",
collapse: "Masquer",
result_toc: "Table des matières",
search_short: "Le mot clé est trop court.",
search_more: "Plus",
search_less: "Moins",
bookmark: "Enregistrez en favori les pages fréquemment affichées pour y accéder rapidement.<br />Pour enregistrer un favori, appuyez sur <img src='../contents/images/template/bookmark_off.png' class='book_icon' /> au bas de l’écran. Cette page sera ajoutée à la liste des favoris.<br /><br /><div id='book_area'><img src='../contents/images/template/bookmark_info.png' class='book_info' /></div>",
close: "Fermer",
bookmark_tit: "Favoris",
basic_tit: "Fonctions de base",
application_tit: "Applications",
setting_tit: "Paramètres",
recom_tit: "Recommandé",
privacy_tit: "Vie privée et sécurité",
connect_tit: "Connectivité",
setting_tit1: "Connexions",
setting_tit2: "Appareil",
setting_tit3: "Personnel",
setting_tit4: "Système",
intro: "Introduction",
bookmark_over: "Vous pouvez ajouter jusqu’à 20 pages à la liste des favoris."
},
"German":{
title: "Benutzerhandbuch",
model: model_all,
search: "Suche",
home: "Start",
list: "Liste",
settings: "Einstellungen",
font_tit: "Schriftgröße",
line_tit: "Zeilenabstand",
view_toc3: "Wichtige Funktionen",
toc_bottom: "Einige Inhalte auf dem Gerät unterscheiden oder ändern sich möglicherweise ohne vorherige Ankündigung.",
keyword: "Suchbegriff eingeben",
recent_key: "Kürzlich verwendete Suchbegriffe",
result: "Keine Ergebnisse.",
expand: "Info",
collapse: "Kurzinfo",
result_toc: "Inhaltsverzeichnis",
search_short: "Der Suchbegriff ist zu kurz.",
search_more: "Optionen",
search_less: "Weniger",
bookmark: "Versehen Sie Seiten, die Sie häufig ansehen, mit einem Lesezeichen, um schnell auf sie zugreifen zu können.<br />Tippen Sie zum Hinzufügen eines Lesezeichens zu einer Seite unten auf dem Bildschirm <img src='../contents/images/template/bookmark_off.png' class='book_icon' /> an. Die Seite wird der Liste mit den Lesezeichen hinzugefügt.<br /><br /><div id='book_area'><img src='../contents/images/template/bookmark_info.png' class='book_info' /></div>",
close: "Schließen",
bookmark_tit: "Favoriten",
basic_tit: "Grundlegende Information",
application_tit: "Anwendungen",
setting_tit: "Einstellungen",
recom_tit: "Empfohlen",
privacy_tit: "Datenschutz und Sicherheit",
connect_tit: "Verbindungen",
setting_tit1: "Verbindungen",
setting_tit2: "Gerät",
setting_tit3: "Persönlich",
setting_tit4: "System",
intro: "Einführung",
bookmark_over: "Sie können der Lesezeichenliste bis zu 20 Seiten hinzufügen."
},
"Greek":{
title: "Εγχειρίδιο χρήσης",
model: model_all,
search: "Αναζήτ.",
home: "Αρχική",
list: "Λίστα",
settings: "Ρυθμίσεις",
font_tit: "Μέγεθος γραμματοσειράς",
line_tit: "Απόσταση γραμμών",
view_toc3: "Βασικά χαρακτηριστικά",
toc_bottom: "Κάποιο μέρος του περιεχομένου στη συσκευή σας ενδέχεται να διαφέρει ή να αλλάξει χωρίς προειδοποίηση.",
keyword: "Εισαγωγή λέξης αναζήτησης",
recent_key: "Πρόσφατες λέξεις κλειδιά",
result: "Δεν βρέθηκαν αποτελέσματα.",
expand: "Ανάπ/ξη.",
collapse: "Σύμ/ξη.",
result_toc: "Πίνακας περιεχομένων",
search_short: "Η λέξη κλειδί είναι πολύ μικρή.",
search_more: "Περισσότ.",
search_less: "Λιγότερα",
bookmark: "Σημειώστε με σελιδοδείκτη τις σελίδες που προβάλλετε συχνά για να έχετε γρήγορη πρόσβαση.<br />Για να σημειώσετε με σελιδοδείκτη μια σελίδα, πατήστε <img src='../contents/images/template/bookmark_off.png' class='book_icon' /> στο κάτω μέρος της οθόνης. Η σελίδα προστίθεται στη λίστα σελιδοδεικτών σας.<br /><br /><div id='book_area'><img src='../contents/images/template/bookmark_info.png' class='book_info' /></div>",
close: "Κλείσιμο",
bookmark_tit: "Σελιδοδείκτες",
basic_tit: "Βασικές λειτουργίες",
application_tit: "Εφαρμογές",
setting_tit: "Ρυθμίσεις",
recom_tit: "Συνιστώμενες",
privacy_tit: "Απόρρητο και ασφάλεια",
connect_tit: "Συνδεσιμότητα",
setting_tit1: "Συνδέσεις",
setting_tit2: "Συσκευή",
setting_tit3: "Προσωπικό",
setting_tit4: "Σύστημα",
intro: "Εισαγωγή",
bookmark_over: "Μπορείτε να προσθέσετε έως και 20 σελίδες στη λίστα σελιδοδεικτών."
},
"HongKong":{
title: "用戶手冊",
model: model_all,
search: "搜尋",
home: "首頁",
list: "清單",
settings: "設定",
font_tit: "字體大小",
line_tit: "行距",
view_toc3: "主要功能",
toc_bottom: "裝置上某些內容可能會有所不同或在沒有事先通知的情況下發生變更。",
keyword: "輸入搜尋關鍵字",
recent_key: "最近的關鍵字。",
result: "找不到結果。",
expand: "展開",
collapse: "收起",
result_toc: "目錄",
search_short: "關鍵字太短。",
search_more: "更多",
search_less: "更少",
bookmark: "將經常檢視的頁面加入至書籤以取得快速存取。<br />若要將頁面加入至書籤，輕觸螢幕底部的 <img src='../contents/images/template/bookmark_off.png' class='book_icon' />。頁面將加入至您的書籤清單。<br /><br /><div id='book_area'><img src='../contents/images/template/bookmark_info.png' class='book_info' /></div>",
close: "關閉",
bookmark_tit: "書籤",
basic_tit: "基本功能",
application_tit: "應用程式",
setting_tit: "設定",
recom_tit: "推薦",
privacy_tit: "隱私與安全",
connect_tit: "連接設定",
setting_tit1: "連接",
setting_tit2: "裝置",
setting_tit3: "個人",
setting_tit4: "系統",
intro: "選項",
bookmark_over: "最多可以將 20 個頁面加入至書籤清單。"
},
"Hungarian":{
title: "Felhasználói kézikönyv",
model: model_all,
search: "Keres",
home: "Kezd",
list: "List",
settings: "Beállítások",
font_tit: "Betűméret",
line_tit: "Sorköz",
view_toc3: "Főbb funkciók",
toc_bottom: "A készüléken található bizonyos tartalmak eltérhetnek vagy értesítés nélkül változhatnak.",
keyword: "Írjon be keresési kulcsszót",
recent_key: "Legutóbbi kulcsszavak",
result: "Nincs találat.",
expand: "Kibont.",
collapse: "Összecsuk.",
result_toc: "Tartalomjegyzék",
search_short: "A kulcsszó túl rövid.",
search_more: "Egyebek",
search_less: "Egyebek nélkül",
bookmark: "Jelölje meg könyvjelzővel a gyakran látogatott oldalakat, így gyorsabban elérheti azokat.<br />Ha szeretne megjelölni egy oldalt könyvjelzővel, érintse meg a képernyő alján található <img src='../contents/images/template/bookmark_off.png' class='book_icon' /> ikont. Az oldal bekerül a könyvjelzők listájába.<br /><br /><div id='book_area'><img src='../contents/images/template/bookmark_info.png' class='book_info' /></div>",
close: "Bezárás",
bookmark_tit: "Könyvjelzők",
basic_tit: "Alapok",
application_tit: "Alkalmazások",
setting_tit: "Beállítások",
recom_tit: "Ajánlott",
privacy_tit: "Adatvédelem és biztonság",
connect_tit: "Csatlakozás",
setting_tit1: "Kapcsolatok",
setting_tit2: "Eszköz",
setting_tit3: "Személyes",
setting_tit4: "Rendszer",
intro: "Bevezető",
bookmark_over: "Legfeljebb 20 oldalt vehet rá a könyvjelzők listájára."
},
"Indonesian":{
title: "Petunjuk Penggunaan",
model: model_all,
search: "Mencari",
home: "Home",
list: "Daftar",
settings: "Aturan",
font_tit: "Ukuran huruf",
line_tit: "Spasi baris",
view_toc3: "Fitur utama",
toc_bottom: "Beberapa konten di perangkat anda mungkin berbeda atau berubah tanpa pemberitahuan.",
keyword: "Masukkan kata kunci pencarian",
recent_key: "Kata kunci terbaru",
result: "Hasil tidak ditemukan.",
expand: "Perluas",
collapse: "Ciut",
result_toc: "Daftar isi",
search_short: "Kata kunci terlalu pendek.",
search_more: "Lainnya",
search_less: "Lebih sedikit",
bookmark: "Tandai halaman yang sering Anda lihat untuk mendapatkan akses cepat.<br />Untuk menandai halaman, ketuk <img src='../contents/images/template/bookmark_off.png' class='book_icon' /> di bagian bawah layar. Halaman akan ditambahkan ke daftar bookmark Anda.<br /><br /><div id='book_area'><img src='../contents/images/template/bookmark_info.png' class='book_info' /></div>",
close: "Tutup",
bookmark_tit: "Bookmark",
basic_tit: "Dasar-dasar",
application_tit: "Aplikasi",
setting_tit: "Pengaturan",
recom_tit: "Disarankan",
privacy_tit: "Privasi dan keselamatan",
connect_tit: "Konektivitas",
setting_tit1: "Koneksi",
setting_tit2: "Perangkat",
setting_tit3: "Pribadi",
setting_tit4: "Sistem",
intro: "Pengantar",
bookmark_over: "Anda dapat menambahkan hingga 20 halaman ke daftar penanda."
},
"Italian":{
title: "Manuale dell'utente",
model: model_all,
search: "Cerca",
home: "Home",
list: "Elenco",
settings: "Impostazioni",
font_tit: "Dimensione caratteri",
line_tit: "Spaziatura linee",
view_toc3: "Funzionalità dei tasti",
toc_bottom: "Alcuni contenuti del dispositivo potrebbero variare o subire modifiche senza preavviso.",
keyword: "Inserite la parola chiave da cercare",
recent_key: "Parole chiave recenti",
result: "Nessun risultato trovato.",
expand: "Più",
collapse: "Meno",
result_toc: "Sommario",
search_short: "La parola chiave è troppo breve.",
search_more: "Altro",
search_less: "Meno",
bookmark: "Aggiungete le pagine più frequentate ai preferiti per un accesso rapido.<br />Per aggiungere una pagina ai preferiti, toccate <img src='../contents/images/template/bookmark_off.png' class='book_icon' /> nella parte inferiore dello schermo. La pagina verrà aggiunta all'elenco preferiti.<br /><br /><div id='book_area'><img src='../contents/images/template/bookmark_info.png' class='book_info' /></div>",
close: "Chiudi",
bookmark_tit: "Preferiti",
basic_tit: "Operazioni di base",
application_tit: "Applicazioni",
setting_tit: "Impostazioni",
recom_tit: "Consigliate",
privacy_tit: "Privacy e sicurezza",
connect_tit: "Connettività",
setting_tit1: "Connessioni",
setting_tit2: "Dispositivo",
setting_tit3: "Personale",
setting_tit4: "Sistema",
intro: "Introduzione",
bookmark_over: "Potete aggiungere fino a 20 pagine all'elenco dei preferiti."
},
"Kazakh":{
title: "Пайдаланушы нұсқаулығы",
model: model_all,
search: "Іздеу",
home: "Бас. бет",
list: "Тізім",
settings: "Параметрлер",
font_tit: "Қаріп өлшемі",
line_tit: "Сызық аралығы",
view_toc3: "Негізгі мүмкіндіктер",
toc_bottom: "Құрылғыдағы біраз мазмұн басқаша болуы немесе ескертусіз өзгертілуі мүмкін.",
keyword: "Іздеу кілтсөзін енгізу",
recent_key: "Соңғы құпиясөздер",
result: "Нәтижелер табылмады.",
expand: "Жаю",
collapse: "Жин.",
result_toc: "Мазмұны",
search_short: "Кілтсөз тым қысқа.",
search_more: "Қосымша",
search_less: "Аз",
bookmark: "Жылдам қатынасу үшін жиі көретін бетбелгі беттері.<br />Бет бетбелгісін жасау үшін экран астындағы <img src='../contents/images/template/bookmark_off.png' class='book_icon' /> түртіңіз. Бет бетбелгілер тізіміне қосылады.<br /><br /><div id='book_area'><img src='../contents/images/template/bookmark_info.png' class='book_info' /></div>",
close: "Жабу",
bookmark_tit: "Бетбелгілер",
basic_tit: "Негіздер",
application_tit: "Қолданбалар",
setting_tit: "Қон-лар",
recom_tit: "Ұсынылған",
privacy_tit: "Құпиялылық және қауіпсіздік",
connect_tit: "Қосылу мүмкіндігі",
setting_tit1: "Қосылымдар",
setting_tit2: "Құрылғы",
setting_tit3: "Жеке",
setting_tit4: "Жүйе",
intro: "Кіріспе",
bookmark_over: "Бетбелгілер тізіміне 20 бетке дейін қосуға болады."
},
"Latvian":{
title: "Lietotāja rokasgrāmata",
model: model_all,
search: "Meklēt",
home: "Sākums",
list: "Liste",
settings: "Iestatījumi",
font_tit: "Fonta izmērs",
line_tit: "Rindstarpa",
view_toc3: "Galvenās funkcijas",
toc_bottom: "Saturs jūsu ierīcē var atšķirties vai mainīties bez iepriekšēja brīdinājuma.",
keyword: "Ievadiet atslēgvārdu meklēšanai",
recent_key: "Pēdējie atslēgvārdi",
result: "Nekas netika atrasts.",
expand: "Izvērst",
collapse: "Īsāk",
result_toc: "Saturs",
search_short: "Atslēgvārds ir pārāk īss.",
search_more: "Citi",
search_less: "Mazāk",
bookmark: "Pievienojiet grāmatzīmēm biežāk skatītās tīmekļa lapas, lai tām varētu ātri piekļūt.<br />Lai pievienotu tīmekļa lapu grāmatzīmēm, ekrāna apakšā pieskarieties <img src='../contents/images/template/bookmark_off.png' class='book_icon' />. Šī tīmekļa lapa tiks pievienota jūsu grāmatzīmju sarakstam.<br /><br /><div id='book_area'><img src='../contents/images/template/bookmark_info.png' class='book_info' /></div>",
close: "Aizvērt",
bookmark_tit: "Grāmatzīmes",
basic_tit: "Pamatinformācija",
application_tit: "Programmas",
setting_tit: "Iestatījumi",
recom_tit: "Ieteicamie",
privacy_tit: "Privātums un drošība",
connect_tit: "Savienojamība",
setting_tit1: "Savienojumi",
setting_tit2: "Ierīce",
setting_tit3: "Privāti",
setting_tit4: "Sistēma",
intro: "Ievads",
bookmark_over: "Grāmatzīmju sarakstam varat pievienot līdz 20 tīmekļa lapām."
},
"Lithuanian":{
title: "Naudotojo vadovas",
model: model_all,
search: "Ieškoti",
home: "Pradžia",
list: "Sąrašas",
settings: "Nustatymai",
font_tit: "Šrifto dydis",
line_tit: "Tarpai tarp linijų",
view_toc3: "Pagrindinės funkcijos",
toc_bottom: "Galimo turinio dalis prietaise gali skirtis ar pakisti iš anksto neįspėjus.",
keyword: "Įvesti paieškos raktažodį",
recent_key: "Neseniai naudoti raktažodžiai",
result: "Rezultatų nerasta.",
expand: "Plėsti",
collapse: "Mažinti",
result_toc: "Turinys",
search_short: "Raktažodis per trumpas.",
search_more: "Daugiau",
search_less: "Mažiau",
bookmark: "Pažymėti puslapiai, kuriuos dažnai peržiūrite greitam prisijungimui.<br />Norėdami pažymėti puslapį, palieskite <img src='../contents/images/template/bookmark_off.png' class='book_icon' /> ekrano apačioje. Puslapis bus pridėtas prie adresyno įrašų sąrašo.<br /><br /><div id='book_area'><img src='../contents/images/template/bookmark_info.png' class='book_info' /></div>",
close: "Uždaryti",
bookmark_tit: "Adresyno įrašai",
basic_tit: "Pagrindai",
application_tit: "Programos",
setting_tit: "Nustatymai",
recom_tit: "Rekomenduojama",
privacy_tit: "Privatumas ir apsauga",
connect_tit: "Jungiamumas",
setting_tit1: "Ryšiai",
setting_tit2: "Įrenginys",
setting_tit3: "Asmeninis",
setting_tit4: "Sistema",
intro: "Įvadas",
bookmark_over: "Žymų sąraše galite pridėti iki 20 lapų."
},
"Macedonian":{
title: "Упатство за корисникот",
model: model_all,
search: "Пребар.",
home: "Дома",
list: "Листа",
settings: "Нагодувања",
font_tit: "Големина на букви",
line_tit: "Проред",
view_toc3: "Главни одлики",
toc_bottom: "Некои содржини на Bашиот уред може да се разликуваат или да се изменат без предупредување.",
keyword: "Внесете клучен збор за пребарување",
recent_key: "Неодамнешни клучни зборови",
result: "Нема резултати.",
expand: "Прош.",
collapse: "Сокриј",
result_toc: "Содржина",
search_short: "Клучниот збор е премногу мал.",
search_more: "Повеќе",
search_less: "Помалку",
bookmark: "Обележете страници што ги прикажувате често за да добиете брз пристап.<br />За да обележите страница, допрете ја <img src='../contents/images/template/bookmark_off.png' class='book_icon' /> во долниот дел од екранот. Страницата ќе се додаде во Вашиот список со сочувани адреси.<br /><br /><div id='book_area'><img src='../contents/images/template/bookmark_info.png' class='book_info' /></div>",
close: "Затвори",
bookmark_tit: "Сочувани адреси",
basic_tit: "Основни информации",
application_tit: "Апликации",
setting_tit: "Опции",
recom_tit: "Препорачано",
privacy_tit: "Приватност и безбедност",
connect_tit: "Поврзливост",
setting_tit1: "Конекции",
setting_tit2: "Уред",
setting_tit3: "Лична",
setting_tit4: "Системски",
intro: "Вовед",
bookmark_over: "Можете да додадете до 20 страници во списокот со зачувани страници."
},
"Norwegian":{
title: "Brukerhåndbok",
model: model_all,
search: "Søk",
home: "Startside",
list: "Liste",
settings: "Innstillinger",
font_tit: "Skriftstørrelse",
line_tit: "Linjeavstand",
view_toc3: "Nøkkelfunksjoner",
toc_bottom: "Noe av innholdet på enheten din kan være forskjellig, eller det kan endres uten forvarsel.",
keyword: "Angi søkeord",
recent_key: "Nylig brukte søkeord",
result: "Ingen resultater funnet.",
expand: "Mer",
collapse: "Mindre",
result_toc: "Innholdsfortegnelse",
search_short: "Søkeordet er for kort.",
search_more: "Mer",
search_less: "Mindre",
bookmark: "Bokmerk sider som du bruker ofte for å få rask tilgang.<br />Du bokmerker en side ved å trykke på <img src='../contents/images/template/bookmark_off.png' class='book_icon' /> nederst på skjermen. Siden vil bli lagt til på bokmerkelisten din.<br /><br /><div id='book_area'><img src='../contents/images/template/bookmark_info.png' class='book_info' /></div>",
close: "Lukk",
bookmark_tit: "Bokmerker",
basic_tit: "Grunnleggende",
application_tit: "Apper",
setting_tit: "Innstillinger",
recom_tit: "Anbefalt",
privacy_tit: "Personvern og sikkerhet",
connect_tit: "Tilkobling",
setting_tit1: "Tilkoblinger",
setting_tit2: "Enhet",
setting_tit3: "Personlig",
setting_tit4: "System",
intro: "Innledning",
bookmark_over: "Du kan legge til opptil 20 sider på bokmerkelisten."
},
"Polish":{
title: "Instrukcja obsługi",
model: model_all,
search: "Szukaj",
home: "Start",
list: "Lista",
settings: "Ustawienia",
font_tit: "Rozmiar czcionki",
line_tit: "Odstęp pomiędzy liniami",
view_toc3: "Najważniejsze funkcje",
toc_bottom: "Część zawartości znajdującej się w urządzeniu może zostać zmieniona bez powiadomienia.",
keyword: "Wprowadź słowo kluczowe wyszukiwania",
recent_key: "Ostatnio używane słowa kluczowe",
result: "Nie znaleziono wyników.",
expand: "Rozw.",
collapse: "Zw.",
result_toc: "Spis treści",
search_short: "Słowo kluczowe jest zbyt krótkie.",
search_more: "Więcej",
search_less: "Mniej",
bookmark: "Dodaj zakładki do często odwiedzanych stron, aby szybko uzyskiwać do nich dostęp.<br />Aby dodać zakładkę do strony, dotknij <img src='../contents/images/template/bookmark_off.png' class='book_icon' /> na górze ekranu. Strona zostanie dodana do listy zakładek.<br /><br /><div id='book_area'><img src='../contents/images/template/bookmark_info.png' class='book_info' /></div>",
close: "Zamknij",
bookmark_tit: "Zakładki",
basic_tit: "Podstawowe informacje",
application_tit: "Aplikacje",
setting_tit: "Ustawienia",
recom_tit: "Polecane",
privacy_tit: "Prywatność i bezpieczeństwo",
connect_tit: "Łączność",
setting_tit1: "Połączenia",
setting_tit2: "Urządzenie",
setting_tit3: "Osobiste",
setting_tit4: "System",
intro: "Wstęp",
bookmark_over: "Możesz dodać do 20 stron na liście zakładek."
},
"Portuguese":{
title: "Manual do utilizador",
model: model_all,
search: "Procurar",
home: "Início",
list: "Lista",
settings: "Definições",
font_tit: "Tamanho da fonte",
line_tit: "Espaçamento entre linhas",
view_toc3: "Funcionalidades das teclas",
toc_bottom: "Algum do conteúdo do seu dispositivo pode ser diferente ou ser alterado sem aviso prévio.",
keyword: "Insira palavra-chave a procurar",
recent_key: "Palavras-chaves recentes",
result: "Sem resultados.",
expand: "Expand.",
collapse: "Recolher",
result_toc: "Índice remissivo",
search_short: "A palavra-chave é muito pequena.",
search_more: "Mais",
search_less: "Menos",
bookmark: "Adicione aos favoritos páginas que visita frequentemente para obter acesso rápido.<br />Para adicionar uma página aos favoritos, toque <img src='../contents/images/template/bookmark_off.png' class='book_icon' /> ao fundo do ecrã. A página será adicionada à sua lista de favoritos.<br /><br /><div id='book_area'><img src='../contents/images/template/bookmark_info.png' class='book_info' /></div>",
close: "Fechar",
bookmark_tit: "Favoritos",
basic_tit: "Básico",
application_tit: "Aplicações",
setting_tit: "Definições",
recom_tit: "Recomendado",
privacy_tit: "Privacidade e segurança",
connect_tit: "Conectividade",
setting_tit1: "Ligações",
setting_tit2: "Dispositivo",
setting_tit3: "Pessoal",
setting_tit4: "Sistema",
intro: "Introdução",
bookmark_over: "Pode adicionar até 20 páginas à lista de favoritos."
},
"PRC Chinese":{
title: "使用说明书",
model: model_all,
search: "搜索",
home: "主页",
list: "列表",
settings: "设定",
font_tit: "字体大小",
line_tit: "行距",
view_toc3: "关键特性",
toc_bottom: "设备上某些内容可能会有所不同或在没有事先通知的情况下发生变更。",
keyword: "输入搜索关键字",
recent_key: "最近的关键字。",
result: "未找到结果。",
expand: "展开",
collapse: "收回",
result_toc: "目录",
search_short: "关键字过短。",
search_more: "更多",
search_less: "更少",
bookmark: "将经常查看的页面添加至书签以实现快速访问。<br />如欲将页面添加至书签，点击屏幕底部的 <img src='../contents/images/template/bookmark_off.png' class='book_icon' />。页面将添加至您的书签列表。<br /><br /><div id='book_area'><img src='../contents/images/template/bookmark_info.png' class='book_info' /></div>",
close: "关闭",
bookmark_tit: "书签",
basic_tit: "基本功能",
application_tit: "应用程序",
setting_tit: "设定",
recom_tit: "推荐",
privacy_tit: "隐私和安全",
connect_tit: "连接功能",
setting_tit1: "连接",
setting_tit2: "设备",
setting_tit3: "个人",
setting_tit4: "系统",
intro: "选项",
bookmark_over: "最多可以将 20 个页面添加至书签列表。"
},
"Romanian":{
title: "Manualul utilizatorului",
model: model_all,
search: "Căutare",
home: "Acasă",
list: "Listă",
settings: "Setări",
font_tit: "Dimensiune font",
line_tit: "Spaţiere rânduri",
view_toc3: "Caracteristici esenţiale",
toc_bottom: "Anumit conţinut de pe dispozitivul dvs. poate fi diferit sau poate fi modificat fără notificare.",
keyword: "Introduceţi cuvânt cheie de căutare",
recent_key: "Cuvinte cheie recente",
result: "Niciun rezultat găsit.",
expand: "Extind.",
collapse: "Restrân.",
result_toc: "Cuprins",
search_short: "Cuvântul cheie este prea scurt.",
search_more: "Mai multe",
search_less: "Mai puţine",
bookmark: "Marcaţi paginile pe care le vizualizaţi frecvent pentru a avea acces rapid.<br />Pentru a marca o pagină, atingeţi <img src='../contents/images/template/bookmark_off.png' class='book_icon' /> din partea de jos a ecranului. Pagina va fi adăugată la lista de marcaje.<br /><br /><div id='book_area'><img src='../contents/images/template/bookmark_info.png' class='book_info' /></div>",
close: "Închidere",
bookmark_tit: "Marcaje",
basic_tit: "Noţiuni de bază",
application_tit: "Aplicaţii",
setting_tit: "Setări",
recom_tit: "Recomandat",
privacy_tit: "Confidenţialitate şi siguranţă",
connect_tit: "Conectivitate",
setting_tit1: "Conexiuni",
setting_tit2: "Dispozitiv",
setting_tit3: "Personal",
setting_tit4: "Sistem",
intro: "Introducere",
bookmark_over: "Puteţi adăuga până la 20 de pagini la lista de marcaje."
},
"Russian":{
title: "Руководство пользователя",
model: model_all,
search: "Поиск",
home: "Домой",
list: "Список",
settings: "Параметры",
font_tit: "Размер шрифта",
line_tit: "Междустрочный интервал",
view_toc3: "Основные возможности",
toc_bottom: "Часть содержимого на вашем устройстве может отличаться или быть изменена без предварительного уведомления.",
keyword: "Введите ключевое слово для поиска",
recent_key: "Последние ключевые слова",
result: "Результатов не найдено.",
expand: "Развер.",
collapse: "Свер.",
result_toc: "Содержание",
search_short: "Ключевое слово слишком короткое.",
search_more: "Опции",
search_less: "Меньше",
bookmark: "Страницы недавно просмотренных закладок для быстрого доступа.<br />Чтобы добавить закладку, нажмите кнопку <img src='../contents/images/template/bookmark_off.png' class='book_icon' /> внизу экрана. Страница будет добавлена в список закладок.<br /><br /><div id='book_area'><img src='../contents/images/template/bookmark_info.png' class='book_info' /></div>",
close: "Закрыть",
bookmark_tit: "Закладки",
basic_tit: "Основные сведения об устройстве",
application_tit: "Приложения",
setting_tit: "Настройки",
recom_tit: "Рекомендуемые",
privacy_tit: "Конфиденциальность и безопасность",
connect_tit: "Подключение",
setting_tit1: "Подключения",
setting_tit2: "Устройство",
setting_tit3: "Личное",
setting_tit4: "Система",
intro: "Введение",
bookmark_over: "В список закладок можно добавить до 20 страниц."
},
"Serbian":{
title: "Uputstvo za upotrebu",
model: model_all,
search: "Traži",
home: "Početna",
list: "Lista",
settings: "Podešavanja",
font_tit: "Veličina fonta",
line_tit: "Prored",
view_toc3: "Ključne karakteristike",
toc_bottom: "Neki sadržaj na vašem uređaju se može razlikovati ili promeniti bez prethodnog obaveštenja.",
keyword: "Unesite ključnu reč pretrage",
recent_key: "Nedavne ključne reči",
result: "Nema pronađenih rezultata.",
expand: "Raširi",
collapse: "Skupi",
result_toc: "Sadržaj",
search_short: "Ključna reč je prekratka.",
search_more: "Još",
search_less: "Manje",
bookmark: "Obeležite stranice koje često gledate radi brzog pristupa.<br />Da biste obeležili stranicu, kucnite na <img src='../contents/images/template/bookmark_off.png' class='book_icon' /> u dnu ekrana. Stranica će biti dodata na vašu listu obeleživača.<br /><br /><div id='book_area'><img src='../contents/images/template/bookmark_info.png' class='book_info' /></div>",
close: "Zatvori",
bookmark_tit: "Obeleživači",
basic_tit: "Osnovne informacije",
application_tit: "Aplikacije",
setting_tit: "Podešavanja",
recom_tit: "Preporučeno",
privacy_tit: "Privatnost i bezbednost",
connect_tit: "Povezivanje",
setting_tit1: "Veze",
setting_tit2: "Uređaj",
setting_tit3: "Lični",
setting_tit4: "Sistem",
intro: "Uvod",
bookmark_over: "Na listu obeleživača možete da dodate do 20 stranica."
},
"Singapore Chinese":{
title: "使用说明书",
model: model_all,
search: "搜索",
home: "主页",
list: "列表",
settings: "设定",
font_tit: "字体大小",
line_tit: "行距",
view_toc3: "主要功能",
toc_bottom: "设备上某些内容可能会有所不同或在不事先通知的情况下发生变更。",
keyword: "输入搜索关键字",
recent_key: "最近的关键字。",
result: "未找到结果。",
expand: "展开",
collapse: "收回",
result_toc: "目录",
search_short: "关键字太短。",
search_more: "更多",
search_less: "更少",
bookmark: "将经常查看的页面添加至书签以便快速访问。<br />如欲将页面添加至书签，点击屏幕底部的 <img src='../contents/images/template/bookmark_off.png' class='book_icon' />。页面将添加至您的书签列表。<br /><br /><div id='book_area'><img src='../contents/images/template/bookmark_info.png' class='book_info' /></div>",
close: "关闭",
bookmark_tit: "书签",
basic_tit: "基本功能",
application_tit: "应用程序",
setting_tit: "设定",
recom_tit: "推荐",
privacy_tit: "隐私和安全",
connect_tit: "连接能力",
setting_tit1: "连接",
setting_tit2: "设备",
setting_tit3: "个人",
setting_tit4: "系统",
intro: "介绍",
bookmark_over: "最多可以将 20 个页面添加至书签列表。"
},
"Slovak":{
title: "Používateľská príručka",
model: model_all,
search: "Hľadať",
home: "Domov",
list: "Zoznam",
settings: "Nastavenia",
font_tit: "Veľkosť písma",
line_tit: "Riadkovanie",
view_toc3: "Hlavné funkcie",
toc_bottom: "Určitý obsah v zariadení sa môže líšiť alebo zmeniť bez upozornenia.",
keyword: "Zadajte kľúčové slová na vyhľadanie",
recent_key: "Posledné kľúčové slová",
result: "Neboli nájdené žiadne výsledky.",
expand: "Rozb.",
collapse: "Zbal.",
result_toc: "Obsah",
search_short: "Kľúčové slovo je príliš krátke.",
search_more: "Ďalšie",
search_less: "Menej",
bookmark: "Pridajte často zobrazované stránky do záložiek, aby ste k nim získali rýchly prístup.<br />Ak chcete pridať stránku do záložiek, ťuknite na <img src='../contents/images/template/bookmark_off.png' class='book_icon' /> v dolnej časti obrazovky. Stránka bude pridaná do zoznamu záložiek.<br /><br /><div id='book_area'><img src='../contents/images/template/bookmark_info.png' class='book_info' /></div>",
close: "Zatvoriť",
bookmark_tit: "Záložky",
basic_tit: "Základy",
application_tit: "Aplikácie",
setting_tit: "Nastavenia",
recom_tit: "Odporúčané",
privacy_tit: "Súkromie a bezpečnosť",
connect_tit: "Pripojenie",
setting_tit1: "Pripojenia",
setting_tit2: "Zariadenie",
setting_tit3: "Osobné",
setting_tit4: "Systém",
intro: "Úvod",
bookmark_over: "Do zoznamu záložiek môžete pridať až 20 strán."
},
"Slovenian":{
title: "Navodila za uporabo",
model: model_all,
search: "Iskanje",
home: "Domov",
list: "Seznam",
settings: "Nastavitve",
font_tit: "Velikost pisave",
line_tit: "Razmik vrstic",
view_toc3: "Ključne funkcije",
toc_bottom: "Nekatera vsebina na vaši napravi se lahko razlikuje ali spremeni brez obvestila.",
keyword: "Vnesite ključno besedo iskanja",
recent_key: "Nedavne ključne besede",
result: "Brez rezultatov.",
expand: "Raz.",
collapse: "Str.",
result_toc: "Kazalo",
search_short: "Ključna beseda je prekratka.",
search_more: "Manj",
search_less: "Less",
bookmark: "Zaznamujte pogosto gledane strani, da omogočite hiter dostop do njih.<br />Da ustvarite zaznamek strani, pritisnite <img src='../contents/images/template/bookmark_off.png' class='book_icon' /> na dnu zaslona. Stran bo dodana na seznam vaših zaznamkov.<br /><br /><div id='book_area'><img src='../contents/images/template/bookmark_info.png' class='book_info' /></div>",
close: "Zapri",
bookmark_tit: "Zaznamki",
basic_tit: "Osnove",
application_tit: "Aplikacije",
setting_tit: "Nastavitve",
recom_tit: "Priporočeno",
privacy_tit: "Zasebnost in varnost",
connect_tit: "Povezljivost",
setting_tit1: "Povezave",
setting_tit2: "Naprava",
setting_tit3: "Osebno",
setting_tit4: "Sistem",
intro: "Uvod",
bookmark_over: "V seznam zaznamkov lahko dodate do 20 strani."
},
"Spanish":{
title: "Manual de usuario",
model: model_all,
search: "Buscar",
home: "Inicio",
list: "Lista",
settings: "Ajustes",
font_tit: "Tamaño de fuente",
line_tit: "Espaciado de línea",
view_toc3: "Funciones de teclas",
toc_bottom: "Ciertos contenidos del dispositivo podrían ser diferentes o cambiar sin previo aviso.",
keyword: "Introduzca palabra clave de búsqueda",
recent_key: "Palabras clave recientes",
result: "No se encontraron resultados.",
expand: "Mostr.",
collapse: "Ocult.",
result_toc: "Índice",
search_short: "La palabra clave es demasiado corta.",
search_more: "Más",
search_less: "Menos",
bookmark: "Marque páginas que ve frecuentemente para acceder a ellas rápidamente.<br />Para marcar una página, pulse <img src='../contents/images/template/bookmark_off.png' class='book_icon' /> en la parte inferior de la pantalla. Se añadirá la página a su lista de marcas.<br /><br /><div id='book_area'><img src='../contents/images/template/bookmark_info.png' class='book_info' /></div>",
close: "Cerrar",
bookmark_tit: "Favoritos",
basic_tit: "Nociones básicas",
application_tit: "Aplicaciones",
setting_tit: "Ajustes",
recom_tit: "Recomendado",
privacy_tit: "Privacidad y seguridad",
connect_tit: "Conectividad",
setting_tit1: "Conexiones",
setting_tit2: "Dispositivo",
setting_tit3: "Personal",
setting_tit4: "Sistema",
intro: "Introducción",
bookmark_over: "Puede añadir hasta 20 páginas a la lista de Favoritos."
},
"Spanish_LA":{
title: "Manual del usuario",
model: model_all,
search: "Buscar",
home: "Inicio",
list: "Lista",
settings: "Config.",
font_tit: "Tamaño de fuente",
line_tit: "Espaciado entre líneas",
view_toc3: "Funciones básicas",
toc_bottom: "Ciertos contenidos del dispositivo podrían ser diferentes o cambiar sin previo aviso.",
keyword: "Ingresar palabra clave de búsqueda",
recent_key: "Palabras clave recientes",
result: "No se encontraron resultados.",
result_toc: "Índice",
search_short: "La palabra clave es demasiado corta.",
search_more: "Más",
search_less: "Menos",
bookmark: "Marque páginas que visita frecuentemente para acceder a ellas rápidamente.<br />Para marcar una página, pulse <img src='../contents/images/template/bookmark_off.png' class='book_icon' /> en la parte inferior de la pantalla. La página se añadirá a la lista de marcadores.<br /><br /><div id='book_area'><img src='../contents/images/template/bookmark_info.png' class='book_info' /></div>",
close: "Cerrar",
bookmark_tit: "Marcadores",
basic_tit: "Nociones básicas",
application_tit: "Aplicaciones",
setting_tit: "Config.",
recom_tit: "Recomendado",
privacy_tit: "Privacidad y seguridad",
connect_tit: "Conectividad",
setting_tit1: "Conexiones",
setting_tit2: "Dispositivo",
setting_tit3: "Personal",
setting_tit4: "Sistema",
intro: "Introducción",
bookmark_over: "Podrá añadir hasta 20 páginas a la lista de marcadores."
},
"Swedish":{
title: "Bruksanvisning",
model: model_all,
search: "Sök",
home: "Startsida",
list: "Lista",
settings: "Inställningar",
font_tit: "Teckenstorlek",
line_tit: "Radavstånd",
view_toc3: "Nyckelfunktioner",
toc_bottom: "Visst innehåll på din enhet kan variera eller ändras utan meddelande.",
keyword: "Ange sökord",
recent_key: "Senaste sökorden",
result: "Inga resultat hittades.",
expand: "Visa",
collapse: "Dölj",
result_toc: "Innehållsförteckning",
search_short: "Sökordet är för kort.",
search_more: "Mer",
search_less: "Mindre",
bookmark: "Bokmärk sidor som du besöker ofta för att få snabb åtkomst.<br />Bokmärk en sida genom att trycka lätt på <img src='../contents/images/template/bookmark_off.png' class='book_icon' /> längst ned på skärmen. Sidan läggs då till i bokmärkeslistan.<br /><br /><div id='book_area'><img src='../contents/images/template/bookmark_info.png' class='book_info' /></div>",
close: "Stäng",
bookmark_tit: "Bokmärken",
basic_tit: "Grunder",
application_tit: "Program",
setting_tit: "Inställningar",
recom_tit: "Rekommenderat",
privacy_tit: "Sekretess och säkerhet",
connect_tit: "Anslutning",
setting_tit1: "Anslutning",
setting_tit2: "Enhet",
setting_tit3: "Personlig",
setting_tit4: "System",
intro: "Inledning",
bookmark_over: "Du kan lägga till upp till 20 sidor i bokmärkeslistan."
},
"Taiwan":{
title: "使用手冊",
model: model_all,
search: "搜尋",
home: "首頁",
list: "清單",
settings: "設定",
font_tit: "字型大小",
line_tit: "行距",
view_toc3: "主要功能",
toc_bottom: "裝置上某些內容可能會有所不同或在不事先通知的情況下發生變更。",
keyword: "輸入搜尋關鍵字",
recent_key: "最近搜尋關鍵字",
result: "找不到結果。",
expand: "展開",
collapse: "收回",
result_toc: "目錄",
search_short: "關鍵字過短。",
search_more: "更多",
search_less: "較少",
bookmark: "將您經常檢視的頁面加入書籤以快速進入。<br />若要加入頁面到書籤，請輕觸螢幕底部的 <img src='../contents/images/template/bookmark_off.png' class='book_icon' />。頁面將加入到您的書籤清單。<br /><br /><div id='book_area'><img src='../contents/images/template/bookmark_info.png' class='book_info' /></div>",
close: "關閉",
bookmark_tit: "書籤",
basic_tit: "基本功能",
application_tit: "應用程式",
setting_tit: "設定",
recom_tit: "推薦",
privacy_tit: "隱私與安全",
connect_tit: "連線",
setting_tit1: "連接",
setting_tit2: "裝置",
setting_tit3: "個人",
setting_tit4: "系統",
intro: "選項",
bookmark_over: "您最多可以新增 20 個網頁至書籤清單。"
},
"Thai":{
title: "คู่มือการใช้งาน",
model: model_all,
search: "ค้นหา",
home: "โฮม",
list: "รายการ",
settings: "การตั้งค่า",
font_tit: "ขนาดตัวอักษร",
line_tit: "ระยะห่างระหว่างบรรทัด",
view_toc3: "คุณสมบัติหลัก",
toc_bottom: "เนื้อหาบางส่วนในเครื่องของคุณอาจแตกต่างออกไป หรืออาจมีการเปลี่ยนแปลงโดยไม่แจ้งให้ทราบ",
keyword: "ป้อนคำสำคัญในการค้นหา",
recent_key: "คำสำคัญล่าสุด",
result: "ไม่พบผลลัพธ์",
expand: "ขยาย",
collapse: "ย่อ",
result_toc: "สารบัญ",
search_short: "คำสำคัญสั้นเกินไป",
search_more: "เพิ่มเติม",
search_less: "น้อยลง",
bookmark: "ทำหน้าบุ๊คมาร์กที่คุณดูอยู่เสมอเพื่อเข้าถึงอย่างรวดเร็ว<br />ในการบุ๊คมาร์กหน้า สัมผัส <img src='../contents/images/template/bookmark_off.png' class='book_icon' /> ด้านล่างของหน้าจอ จะเพิ่มหน้าลงในรายการบุ๊คมาร์กของคุณ<br /><br /><div id='book_area'><img src='../contents/images/template/bookmark_info.png' class='book_info' /></div>",
close: "ปิด",
bookmark_tit: "บุ๊คมาร์ก",
basic_tit: "เบื้องต้น",
application_tit: "แอพพลิเคชั่น",
setting_tit: "การตั้งค่า",
recom_tit: "แนะนำ",
privacy_tit: "ความเป็นส่วนตัวและความปลอดภัย",
connect_tit: "การเชื่อมต่อ",
setting_tit1: "การเชื่อมต่อ",
setting_tit2: "อุปกรณ์",
setting_tit3: "ส่วนตัว",
setting_tit4: "ระบบ",
intro: "บทนำ",
bookmark_over: "สามารถเพิ่มในรายการบุ๊กมาร์กได้ถึง 20 หน้า"
},
"Turkish":{
title: "Kullanım Kılavuzu <br /><span class='tur_sub_tit'>Cep Telefonu</span>",
model: model_all,
search: "Ara",
home: "Anasayfa",
list: "Liste",
settings: "Ayarlar",
font_tit: "Yazı tipi büyüklüğü",
line_tit: "Satır boşluğu",
view_toc3: "Önemli özellikler",
toc_bottom: "Cihazınızdaki bazı içerikler farklılık gösterebilir veya bildirim verilmeden değiştirilebilir.",
keyword: "Aranacak anahtar kelimeyi girin",
recent_key: "Son anahtar kelimeler",
result: "Sonuç bulunamadı.",
expand: "Genişl.",
collapse: "Darlt.",
result_toc: "İçindekiler",
search_short: "Anahtar kelime çok kısa.",
search_more: "Diğer",
search_less: "Daha az",
bookmark: "Hızlı erişim için sık görüntülediğiniz sayfaları sık kullanılanlara ekleyin.<br />Bir sayfayı sık kullanılanlara eklemek için ekranın altındaki <img src='../contents/images/template/bookmark_off.png' class='book_icon' /> üzerine dokunun. Sayfa, sık kullanılanlar listenize eklenecektir.<br /><br /><div id='book_area'><img src='../contents/images/template/bookmark_info.png' class='book_info' /></div>",
close: "Kapat",
bookmark_tit: "Yer imleri",
basic_tit: "Temel hususlar",
application_tit: "Uygulamalar",
setting_tit: "Ayarlar",
recom_tit: "Önerilen",
privacy_tit: "Gizlilik ve güvenlik",
connect_tit: "Bağlanabilirlik",
setting_tit1: "Bağlantılar",
setting_tit2: "Cihaz",
setting_tit3: "Kişisel",
setting_tit4: "Sistem",
intro: "Tanıtım",
bookmark_over: "Sık kullanılanlar listesine 20 adede kadar sayfa ekleyebilirsiniz."
},
"Ukrainian":{
title: "Посібник користувача",
model: model_all,
search: "Пошук",
home: "Дом.ст.",
list: "Список",
settings: "Налаштування",
font_tit: "Розмір шрифту",
line_tit: "Міжрядковий інтервал",
view_toc3: "Основні функції",
toc_bottom: "Деякий вміст може не відповідати чи бути змінений на пристрої без завчасного попередження.",
keyword: "Введіть ключове слово пошуку",
recent_key: "Останні ключові слова",
result: "Жодного результату не знайдено.",
expand: "Розгор.",
collapse: "Згор.",
result_toc: "Зміст",
search_short: "Ключове слово задовге.",
search_more: "Додатково",
search_less: "Менше",
bookmark: "Сторінки закладок, що переглядали найчастіше для отримання швидкого доступу.<br />Щоб створити закладку, торкніться <img src='../contents/images/template/bookmark_off.png' class='book_icon' /> внизу екрана. Сторінку буде додано до списку закладок.<br /><br /><div id='book_area'><img src='../contents/images/template/bookmark_info.png' class='book_info' /></div>",
close: "Закрити",
bookmark_tit: "Закладки",
basic_tit: "Основні прийоми роботи",
application_tit: "Програми",
setting_tit: "Налаштування",
recom_tit: "Рекомендовані",
privacy_tit: "Конфіденційність і безпека",
connect_tit: "Підключення",
setting_tit1: "Підключення",
setting_tit2: "Пристрій",
setting_tit3: "Особисте",
setting_tit4: "Система",
intro: "Вступ",
bookmark_over: "Можна додати до 20 сторінок до списку закладок."
},
"Urdu":{
title: "صارف گائیڈ",
model: model_all,
search: "سرچ",
home: "ہوم",
list: "فہرست",
settings: "سیٹنگز",
font_tit: "فونٹ سائز",
line_tit: "سطری فاصلہ بندی",
view_toc3: "اہم خصوصیات",
toc_bottom: "آپ کے آلہ پر کچھ مشمول میں فرق ہوسکتا ہے یا بغیر نوٹس تبدیل ہوسکتے ہیں۔",
keyword: "تلاش کا کلیدی لفظ درج کریں",
recent_key: "حالیہ کلیدی الفاظ",
result: "کوئی نتائج نہیں ملے۔",
expand: "وسیع",
collapse: "مختصر",
result_toc: "مشمولات کا جدول",
search_short: "کلیدی لفظ بہت مختصر ہے۔",
search_more: "اور",
search_less: "کم",
bookmark: "جن صفحات کو اکثر دیکھتے ہیں ان تک فوری رسائی حاصل کرنے کے لیے بک مارک کریں۔<br />کسی صفحہ کو بک مارک کرنے کے لیے، اسکرین کے چنلے حصے میں تھپتھپائیں <img src='../contents/images/template/bookmark_off.png' class='book_icon' />۔ صفحہ آپ کی بک مارک فہرست میں شامل کر دیا جائے گا۔<br /><br /><div id='book_area'><img src='../contents/images/template/bookmark_info.png' class='book_info' /></div>",
close: "بند کریں",
bookmark_tit: "بک مارک",
basic_tit: "بنیادی باتیں",
application_tit: "ایپلیکیشنز",
setting_tit: "سیٹنگز",
recom_tit: "مجوزہ",
privacy_tit: "رازداری اور حفاظت",
connect_tit: "کنیکٹویٹی",
setting_tit1: "کنکشنز",
setting_tit2: "آلہ",
setting_tit3: "ذاتی",
setting_tit4: "سسٹم",
intro: "تعارف",
bookmark_over: "آپ بک مارکس فہرست 20 صفحات تک شامل کر سکتے ہیں۔"
},
"Uzbek":{
title: "Foydalanuvchi qo‘llanmasi",
model: model_all,
search: "Qidirish",
home: "Asosiy",
list: "Ro‘yxat",
settings: "Parametrlar",
font_tit: "Shrift o‘lchami",
line_tit: "Starlararo masofa",
view_toc3: "Tugma funksiyalari",
toc_bottom: "Qurilmangizdagi ba’zi tarkib farq qilishi yoki ogohlantirishsiz o‘zgartirilishi mumkin.",
keyword: "Qidirish kalit so‘zini kiriting",
recent_key: "So‘nggi kalit so‘zlar",
result: "Natijalar topilmadi.",
expand: "Keng.",
collapse: "O‘ra.",
result_toc: "Mundarija",
search_short: "Kalit so‘z juda qisqa.",
search_more: "Yana",
search_less: "Kamroq",
bookmark: "Ko‘p tashrif buyuradigan sahifalarga tezroq kirish uchun ularga xatcho‘p qo‘ying.<br />Sahifaga xatcho‘p qo‘yish uchun ekranning quyi qismidagi <img src='../contents/images/template/bookmark_off.png' class='book_icon' /> ga teging. Sahifa xatcho‘plaringiz ro‘yxatiga qo‘shiladi.<br /><br /><div id='book_area'><img src='../contents/images/template/bookmark_info.png' class='book_info' /></div>",
close: "Yopish",
bookmark_tit: "Xatcho‘plar",
basic_tit: "Asosiy ma’lumotlar",
application_tit: "Ilovalar",
setting_tit: "Parametrlar",
recom_tit: "Tavsiya etilgan",
privacy_tit: "Maxfiylik va xavfsizlik",
connect_tit: "Ulanish imkoniyati",
setting_tit1: "Ulanishlar",
setting_tit2: "Qurilma",
setting_tit3: "Shaxsiy",
setting_tit4: "Tizim",
intro: "Kirish",
bookmark_over: "Xatcho‘plar ro‘yxatiga ko‘pi bilan 20 ta sahifa qo‘shishingiz mumkin."
},
"Vietnamese":{
title: "Sách hướng dẫn sử dụng",
model: model_all,
search: "T.kiếm",
home: "Tr.chủ",
list: "D.sách",
settings: "Cài đặt",
font_tit: "Kích thước font",
line_tit: "Khoảng cách dòng",
view_toc3: "Các tính năng chính",
toc_bottom: "Một số nội dung trên thiết bị có thể khác hoặc có thay đổi mà không phải thông báo.",
keyword: "Nhập từ khóa tìm kiếm",
recent_key: "Các từ khóa gần đây",
result: "Không tìm thấy kết quả nào.",
expand: "M.rộng",
collapse: "T.gọn",
result_toc: "Mục lục",
search_short: "Từ khóa quá ngắn.",
search_more: "Nhiều hơn",
search_less: "Ít hơn",
bookmark: "Đánh dấu các trang bạn hay xem để truy cập nhanh.<br />Để đánh dấu trang, chạm vào <img src='../contents/images/template/bookmark_off.png' class='book_icon' /> ở cuối màn hình. Trang sẽ được thêm vào danh sách đánh dấu.<br /><br /><div id='book_area'><img src='../contents/images/template/bookmark_info.png' class='book_info' /></div>",
close: "Đóng",
bookmark_tit: "Trang hay dùng",
basic_tit: "Thông tin cơ bản",
application_tit: "Ứng dụng",
setting_tit: "Cài đặt",
recom_tit: "Khuyến nghị",
privacy_tit: "Bảo mật và an toàn",
connect_tit: "Kết nối",
setting_tit1: "Kết nối",
setting_tit2: "Thiết bị",
setting_tit3: "Cá nhân",
setting_tit4: "Hệ thống",
intro: "Giới thiệu",
bookmark_over: "Bạn có thể thêm tối đa 20 trang vào danh sách dấu trang."
},
"Hebrew":{
title: "מדריך למשתמש",
model: model_all,
search: "חיפוש",
home: "דף הבית",
list: "רשימה",
settings: "הגדרות",
font_tit: "גודל גופן",
line_tit: "מרווח שורה",
view_toc3: "מאפיינים מרכזיים",
toc_bottom: "תכנים מסוימים במכשירך עלולים להשתנות ללא הודעה מוקדמת.",
keyword: "הקלד מילות חיפוש",
recent_key: "מילות חיפוש אחרונות",
result: "לא נמצאו תוצאות.",
expand: "הרחב",
collapse: "כווץ",
result_toc: "תוכן העניינים",
search_short: "מילת חיפוש קצרה מדי.",
search_more: "עוד",
search_less: "פחות",
bookmark: "הוסף עמודים שאתה צופה בהם בתדירות לסימניות לגישה מהירה.<br />להוספת עמוד לסימניות, הקש על <img src='../contents/images/template/bookmark_off.png' class='book_icon' /> בתחתית המסך. העמוד יתווסף לרשימת הסימניות שלך.<br /><br /><div id='book_area'><img src='../contents/images/template/bookmark_info.png' class='book_info' /></div>",
close: "סגור",
bookmark_tit: "סימניות",
basic_tit: "פעולות בסיסיות",
application_tit: "יישומים",
setting_tit: "הגדרות",
recom_tit: "מומלץ",
privacy_tit: "פרטיות ובטיחות",
connect_tit: "קישוריות",
setting_tit1: "חיבורים",
setting_tit2: "מכשיר",
setting_tit3: "אישי",
setting_tit4: "מערכת",
intro: "מבוא",
bookmark_over: "ניתן להוסיף עד 20 עמודים לרשימת הסימניות."
}
};